<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <!-- The same assembly name and the same preprocessor symbols as SharedV1. See the comment there. -->
        <AssemblyName>Shared</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Metalama.Framework" />
    </ItemGroup>

</Project>
