// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.*
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.11"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)
    buildType(UpstreamMerge)
    buildType(RunAllTestArchives)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment,UpstreamMerge,RunAllTestArchives)

    subProject(DockerTests)
    subProject(PlatformTests)

    subProjectsOrder = arrayListOf(DockerTests,PlatformTests)

}

object DebugBuild : BuildType({

    name = "Build [Debug]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
+:artifacts/tests/*.zip=>artifacts/tests
-:%system.teamcity.build.tempDir%/Metalama/CrashReports/**/*.dmp=>logs
+:%system.teamcity.build.tempDir%/Metalama/CrashReports/**/*=>logs
+:%system.teamcity.build.tempDir%/Metalama/Extract/**/.completed=>logs
+:%system.teamcity.build.tempDir%/Metalama/ExtractExceptions/**/*=>logs"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "60")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Debug --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
        commitStatusPublisher {
            vcsRootExtId = "Metalama_Metalama20261_Metalama"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Metalama_Metalama20261_Metalama"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2026.1"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

    triggers {
        vcs {
            watchChangesInDependencies = true
            branchFilter = "+:develop/2026.1"
             quietPeriodMode = VcsTrigger.QuietPeriodMode.USE_CUSTOM
             quietPeriod = 7200
            // Build will not trigger automatically if the commit message contains comment value.
            triggerRules = "-:comment=<<VERSION_BUMP>>|<<DEPENDENCIES_UPDATED>>:**"
        }
    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object ReleaseBuild : BuildType({

    name = "Build [Release]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "60")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Release --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
        commitStatusPublisher {
            vcsRootExtId = "Metalama_Metalama20261_Metalama"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Metalama_Metalama20261_Metalama"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2026.1"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object PublicBuild : BuildType({

    name = "Build [Public]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "60")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% test --configuration Public --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
        commitStatusPublisher {
            vcsRootExtId = "Metalama_Metalama20261_Metalama"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = vcsRoot()
            }
        }
        pullRequests {
            vcsRootExtId = "Metalama_Metalama20261_Metalama"
            provider = github {
                authType = vcsRoot()
                filterTargetBranch = "+:refs/heads/develop/2026.1"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "Publish.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% publish --configuration Public --deployment default --timeout %Publish.Timeout% %Publish.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicDeployment")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(PublicBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(PublicBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object UpstreamMerge : BuildType({

    name = "Upstream Merge"

    params {
        text(
            "UpstreamMerge.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Merge upstream' build step.", allowEmpty = true)
        param("UpstreamMerge.Timeout", "15")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 -Dockerfile eng/docker/claude.Dockerfile "
        }
        powerShell {
            name = "Merge upstream"
            id = "UpstreamMerge"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -Dockerfile eng/docker/claude.Dockerfile -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% -Snapshot upstream-merge --timeout %UpstreamMerge.Timeout% %UpstreamMerge.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

})

object RunAllTestArchives : BuildType({

    name = "Run All Test Archives"

    type = Type.COMPOSITE

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
        showDependenciesChanges = true
     checkoutMode = CheckoutMode.ON_AGENT
    }

    features {
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(PlatformTestLinuxX64Net80) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(PlatformTestMacOsArm64Net80) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
     }

})

object DockerTestsWindowsX64 : BuildType({

    name = "Docker Tests (Windows x64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunDockerTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunDockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Metalama.version.props`\" /><Import Project=`\"../dependencies/Metalama.Compiler/Metalama.Compiler.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute eng/RunDockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunDockerTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform win-x64 %Exec.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        doesNotContain("env.PROCESSOR_IDENTIFIER", "ARMv8")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object DockerTestsLinuxX64 : BuildType({

    name = "Docker Tests (Linux x64)"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunDockerTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunDockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Metalama.version.props`\" /><Import Project=`\"../dependencies/Metalama.Compiler/Metalama.Compiler.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Execute eng/RunDockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunDockerTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform linux-x64 %Exec.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Linux")
        equals("teamcity.agent.jvm.os.arch", "amd64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object RunAllDockerTests : BuildType({

    name = "Run All Docker Tests"

    type = Type.COMPOSITE

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
        showDependenciesChanges = true
     checkoutMode = CheckoutMode.ON_AGENT
    }

    features {
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(DockerTestsWindowsX64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(DockerTestsLinuxX64) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
     }

})

object PlatformTestLinuxX64Net80 : BuildType({

    name = "Platform Tests Linux x64: net8.0"

    artifactRules = """+:artifacts/testResults/**/*=>artifacts/testResults"""

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-DeferToContainer "
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1-platformtestlinuxx64net80"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1-platformtestlinuxx64net80 -Dockerfile eng/docker/linux-x64-build.Dockerfile "
        }
        powerShell {
            name = "Execute eng/RunTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script eng/RunTests.ps1 -ImageName metalama-2026.1-platformtestlinuxx64net80 -Dockerfile eng/docker/linux-x64-build.Dockerfile -NoBuildImage -Label %system.teamcity.buildType.id%_%build.number% -Platform linux-x64 %Exec.Arguments%"
        }
        powerShell {
            name = "Clean up the build agent"
            id = "DockerCleanup"
            executionMode = BuildStep.ExecutionMode.ALWAYS
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = "-After -BuildLabel %system.teamcity.buildType.id%_%build.number% "
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Linux")
        equals("teamcity.agent.jvm.os.arch", "amd64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/tests/Metalama.Framework.PlatformTests.net8.0.zip=>artifacts/tests"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/Metalama.Compiler.Sdk.*.nupkg=>artifacts/test-packages/Metalama.Compiler"
        }
     }

})

object PlatformTestMacOsArm64Net80 : BuildType({

    name = "Platform Tests macOS ARM64: net8.0"

    artifactRules = """+:artifacts/testResults/**/*=>artifacts/testResults"""

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="eng/RunTests.ps1 Arguments",
            description = "Arguments to append to the 'Execute eng/RunTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Clean NuGet cache of produced and dependency packages"
            id = "CleanNuGetCache"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/CleanUpBuildAgent.ps1"
            }
            noProfile = false
            scriptArgs = " "
        }
        powerShell {
            name = "Execute eng/RunTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "eng/RunTests.ps1"
            }
            noProfile = false
            scriptArgs = "-Platform osx-arm64 %Exec.Arguments%"
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Mac OS X")
        equals("teamcity.agent.jvm.os.arch", "aarch64")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
        gitHubAppBuildScopedToken {
            parameterName = "env.GITHUB_TOKEN"
            connectionId = "%GITHUB_CONNECTION_METALAMA%"
            targetRepositories = "Metalama"
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/tests/Metalama.Framework.PlatformTests.net8.0.zip=>artifacts/tests"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/Metalama.Compiler.Sdk.*.nupkg=>artifacts/test-packages/Metalama.Compiler"
        }
     }

})

object DockerTests : Project({

    name = "Docker Tests"

    buildType(DockerTestsWindowsX64)
    buildType(DockerTestsLinuxX64)
    buildType(RunAllDockerTests)

    buildTypesOrder = arrayListOf(DockerTestsWindowsX64,DockerTestsLinuxX64,RunAllDockerTests)

})
object PlatformTests : Project({

    name = "Platform Tests"

    buildType(PlatformTestLinuxX64Net80)
    buildType(PlatformTestMacOsArm64Net80)

    buildTypesOrder = arrayListOf(PlatformTestLinuxX64Net80,PlatformTestMacOsArm64Net80)

})
