// This file is automatically generated by `Build.ps1 generate-scripts`.

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.*
import jetbrains.buildServer.configs.kotlin.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.failureConditions.*
import jetbrains.buildServer.configs.kotlin.triggers.*
import jetbrains.buildServer.configs.kotlin.projectFeatures.*

version = "2025.07"

project {

    buildType(DebugBuild)
    buildType(ReleaseBuild)
    buildType(PublicBuild)
    buildType(PublicDeployment)
    buildType(UpstreamMerge)
    buildType(DockerTestsWinX64)
    buildType(DockerTestsWslX64)

    buildTypesOrder = arrayListOf(DebugBuild,ReleaseBuild,PublicBuild,PublicDeployment,UpstreamMerge,DockerTestsWinX64,DockerTestsWslX64)

}

object DebugBuild : BuildType({

    name = "Build [Debug]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
-:%system.teamcity.build.tempDir%/Metalama/CrashReports/**/*.dmp=>logs
+:%system.teamcity.build.tempDir%/Metalama/CrashReports/**/*=>logs
+:%system.teamcity.build.tempDir%/Metalama/Extract/**/.completed=>logs
+:%system.teamcity.build.tempDir%/Metalama/ExtractExceptions/**/*=>logs"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage test --configuration Debug --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Metalama_Metalama20261_Metalama"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Metalama_Metalama20261_Metalama"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2026.1"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    triggers {
        vcs {
            watchChangesInDependencies = true
            branchFilter = "+:develop/2026.1"
             quietPeriodMode = VcsTrigger.QuietPeriodMode.USE_CUSTOM
             quietPeriod = 7200
            // Build will not trigger automatically if the commit message contains comment value.
            triggerRules = "-:comment=<<VERSION_BUMP>>|<<DEPENDENCIES_UPDATED>>:**"
        }
    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object ReleaseBuild : BuildType({

    name = "Build [Release]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage test --configuration Release --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Metalama_Metalama20261_Metalama"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Metalama_Metalama20261_Metalama"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2026.1"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object PublicBuild : BuildType({

    name = "Build [Public]"

    artifactRules = """+:artifacts/publish/public/**/*=>artifacts/publish/public
+:artifacts/publish/private/**/*=>artifacts/publish/private
+:artifacts/testResults/**/*=>artifacts/testResults
+:artifacts/logs/**/*=>logs
+:artifacts/dumps/**/*=>dumps
"""

    params {
        text(
            "Build.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Build' build step.", allowEmpty = true)
        param("Build.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Build"
            id = "Build"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage test --configuration Public --buildNumber %build.number% --buildType %system.teamcity.buildType.id% --timeout %Build.Timeout% %Build.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    commitStatusPublisher {
        vcsRootExtId = "Metalama_Metalama20261_Metalama"
        publisher = github {
            githubUrl = "https://api.github.com"
            authType = personalToken {
                token = "%env.GITHUB_TOKEN%"
            }
        }
    }
pullRequests {
       vcsRootExtId = "Metalama_Metalama20261_Metalama"
        provider = github {
            authType = token {
                token = "%env.GITHUB_TOKEN%"
            }
           filterTargetBranch = "+:refs/heads/develop/2026.1"
           filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
       }
   }


    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object PublicDeployment : BuildType({

    name = "Deploy [Public]"

    type = Type.DEPLOYMENT

    params {
        text(
            "Publish.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Publish' build step.", allowEmpty = true)
        param("Publish.Timeout", "30")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 "
        }
        powerShell {
            name = "Publish"
            id = "Publish"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -NoBuildImage publish --configuration Public --timeout %Publish.Timeout% %Publish.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_PublicDeployment")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }
        snapshot(PublicBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(PublicBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/public/**/*=>artifacts/publish/public\n+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
     }

})

object UpstreamMerge : BuildType({

    name = "Upstream Merge"

    params {
        text(
            "UpstreamMerge.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Merge upstream' build step.", allowEmpty = true)
        param("UpstreamMerge.Timeout", "15")
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Prepare Docker image metalama-2026.1"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1 -Dockerfile Dockerfile.claude "
        }
        powerShell {
            name = "Merge upstream"
            id = "UpstreamMerge"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script Build.ps1 -ImageName metalama-2026.1 -Dockerfile Dockerfile.claude -NoBuildImage -Snapshot upstream-merge --timeout %UpstreamMerge.Timeout% %UpstreamMerge.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

})

object DockerTestsWinX64 : BuildType({

    name = "Docker-based tests on Windows X64"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute .\\Metalama.Framework\\src\\tests\\docker\\DockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Metalama.version.props`\" /><Import Project=`\"../dependencies/Metalama.Compiler/Metalama.Compiler.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1-dockertestswinx64"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1-dockertestswinx64 "
        }
        powerShell {
            name = "Execute .\\Metalama.Framework\\src\\tests\\docker\\DockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script .\\Metalama.Framework\\src\\tests\\docker\\DockerTests.ps1 -ImageName metalama-2026.1-dockertestswinx64 -NoBuildImage win-x64 %Exec.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

object DockerTestsWslX64 : BuildType({

    name = "Docker-based tests on WSL X64"

    params {
        text(
            "Exec.Arguments", 
            "", 
            label ="DockerBuild.ps1 Arguments",
            description = "Arguments to append to the 'Execute ./Metalama.Framework/src/tests/docker/DockerTests.ps1' build step.", allowEmpty = true)
    }

    vcs {
        root(AbsoluteId("Metalama_Metalama20261_Metalama"))
     checkoutMode = CheckoutMode.ON_AGENT
    }

    steps {
        powerShell {
            name = "Copy nuget.restored.config to nuget.config"
            id = "CopyNuGetConfig"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.config\" -Force;Copy-Item -Path \"artifacts/publish/private/nuget.restored.config\" -Destination \"nuget.wsl.config\" -Force;"
            }
            noProfile = false
        }
        powerShell {
            name = "Create eng/Versions.g.props"
            id = "CreateVersionsFile"
            edition = PowerShellStep.Edition.Core
            scriptMode = script {
                content = "New-Item -Path \"eng/Versions.g.props\" -ItemType File -Force -Value \"<Project><Import Project=`\"../artifacts/publish/private/Metalama.version.props`\" /><Import Project=`\"../dependencies/Metalama.Compiler/Metalama.Compiler.version.props`\" /></Project>\" | Out-Null;"
            }
            noProfile = false
        }
        powerShell {
            name = "Prepare Docker image metalama-2026.1-dockertestswslx64"
            id = "PrepareImage"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-BuildImage -ImageName metalama-2026.1-dockertestswslx64 "
        }
        powerShell {
            name = "Execute ./Metalama.Framework/src/tests/docker/DockerTests.ps1"
            id = "Exec"
            edition = PowerShellStep.Edition.Core
            scriptMode = file {
                path = "DockerBuild.ps1"
            }
            noProfile = false
            scriptArgs = "-Script ./Metalama.Framework/src/tests/docker/DockerTests.ps1 -ImageName metalama-2026.1-dockertestswslx64 -NoBuildImage linux-x64 -Wsl %Exec.Arguments%"
        }
    }

    requirements {
        matches("teamcity.agent.jvm.os.family", "Windows")
        matches("teamcity.agent.jvm.os.arch", "amd64")
        equals("env.BuildAgentType", "docker-win-x64-md")
    }

    features {
        swabra {
            filesCleanup = Swabra.FilesCleanup.BEFORE_BUILD
            lockingProcesses = Swabra.LockingProcessPolicy.KILL
            verbose = true
        }
    }

    dependencies {
        snapshot(DebugBuild) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(DebugBuild) { 
            cleanDestination = true
            artifactRules = "+:artifacts/publish/private/**/*=>artifacts/publish/private"
        }
        snapshot(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) {
                 onDependencyFailure = FailureAction.FAIL_TO_START
        }

        artifacts(AbsoluteId("Metalama_Metalama20261_MetalamaCompiler_ReleaseBuild")) { 
            cleanDestination = true
            artifactRules = "+:artifacts/packages/Release/Shipping/**/*=>dependencies/Metalama.Compiler"
        }
     }

})

