<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- The version built by this repository. -->
        <PackageReference Include="Metalama.Framework" />
    </ItemGroup>

</Project>
