// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.IO;

namespace Metalama.Framework.Engine.Utilities.Roslyn;

/// <summary>
/// Determines whether a syntax tree is generated code, with the rules that Roslyn applies to the files of a project.
/// </summary>
/// <remarks>
/// <para>
/// The classifier of Roslyn is internal, so its rules are replicated: the file-name suffixes <c>.designer.cs</c>, <c>.generated.cs</c>, <c>.g.cs</c>
/// and <c>.g.i.cs</c>, the prefix <c>TemporaryGeneratedFile_</c>, and a leading comment that contains <c>&lt;auto-generated</c> or
/// <c>&lt;autogenerated</c>.
/// </para>
/// <para>
/// This is a different question from <see cref="SourceGeneratorHelper.IsGeneratedFile"/>, which recognizes the documents that the Metalama source
/// generator produces.
/// </para>
/// </remarks>
[PublicAPI]
public static class GeneratedCodeClassifier
{
    /// <summary>
    /// The file-name suffixes of generated files.
    /// </summary>
    private static readonly string[] _suffixes = [".designer.cs", ".generated.cs", ".g.cs", ".g.i.cs"];

    /// <summary>
    /// Determines whether a syntax tree is generated code, from its file name or from its leading comments.
    /// </summary>
    public static bool IsGenerated( SyntaxTree tree )
    {
        var fileName = Path.GetFileName( tree.FilePath );

        if ( !string.IsNullOrEmpty( fileName ) )
        {
            if ( fileName.StartsWith( "TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase ) )
            {
                return true;
            }

            foreach ( var suffix in _suffixes )
            {
                if ( fileName.EndsWith( suffix, StringComparison.OrdinalIgnoreCase ) )
                {
                    return true;
                }
            }
        }

        foreach ( var trivia in tree.GetRoot().GetLeadingTrivia() )
        {
            if ( trivia.IsKind( SyntaxKind.SingleLineCommentTrivia ) || trivia.IsKind( SyntaxKind.MultiLineCommentTrivia ) )
            {
                var text = trivia.ToString();

                if ( text.IndexOf( "<auto-generated", StringComparison.Ordinal ) >= 0 || text.IndexOf( "<autogenerated", StringComparison.Ordinal ) >= 0 )
                {
                    return true;
                }
            }
            else if ( !trivia.IsKind( SyntaxKind.WhitespaceTrivia ) && !trivia.IsKind( SyntaxKind.EndOfLineTrivia ) )
            {
                break;
            }
        }

        return false;
    }
}
