// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.GenerateMetaSyntaxRewriter.Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Metalama.Framework.GenerateMetaSyntaxRewriter;

internal sealed class Generator
{
    private readonly SyntaxDocument _syntax;
    private readonly string _targetDirectory;

    private const string _autoGeneratedHeader =
        """
        // <auto-generated>
        // This code was generated by a the Prepare step of BuildMetalama.csproj from Syntax-*.xml files.
        // </auto-generated>
        """;

    private static string RemoveSuffix( string s, string suffix )
        => s.EndsWith( suffix, StringComparison.Ordinal ) ? s.Substring( 0, s.Length - suffix.Length ) : s;

    public Generator( SyntaxDocument syntax, string targetDirectory )
    {
        this._syntax = syntax;
        this._targetDirectory = targetDirectory;
    }

    private static void CreateDirectoryForFile( string path )
    {
        var directory = Path.GetDirectoryName( path )!;

        if ( !Directory.Exists( directory ) )
        {
            Directory.CreateDirectory( directory );
        }
    }

    public void GenerateTemplateFiles( string path, SyntaxDocument[] versions )
    {
        var targetFile = Path.GetFullPath( Path.Combine( this._targetDirectory, path ) );
        CreateDirectoryForFile( targetFile );

        Console.WriteLine( "Creating " + targetFile );

        using var writer = File.CreateText( targetFile );

        WriteUsings( writer );
        writer.WriteLine();
        writer.WriteLine( "namespace Metalama.Framework.Engine.Templating;" );
        writer.WriteLine();
        this.GenerateMetaSyntaxRewriter( writer, versions );

        // Generate MetaSyntaxFactoryImpl.
        this.GenerateMetaSyntaxFactory( writer );
        writer.Write( "}" );
    }

    public void GenerateRoslynApiVersionEnum( string path, string[] deprecatedVersionNames, SyntaxDocument[] versions )
    {
        var targetFile = Path.GetFullPath( Path.Combine( this._targetDirectory, path ) );
        CreateDirectoryForFile( targetFile );

        Console.WriteLine( "Creating " + targetFile );

        using var writer = File.CreateText( targetFile );

        WriteUsings( writer );
        writer.WriteLine();
        writer.WriteLine( "namespace Metalama.Framework.Engine.CompileTime;" );
        writer.WriteLine();

        writer.WriteLine( "internal enum RoslynApiVersion " );
        writer.WriteLine( "{" );

        for ( var i = 0; i < deprecatedVersionNames.Length; i++ )
        {
            var deprecatedVersion = deprecatedVersionNames[i];
            writer.WriteLine( "\t[Obsolete]" );
            writer.WriteLine( $"\t{deprecatedVersion} = {i}," );
        }

        foreach ( var version in versions )
        {
            writer.WriteLine( $"\t{version.Version.EnumValue} = {version.Version.Index + deprecatedVersionNames.Length}," );
        }

        writer.WriteLine( $"\tCurrent = {this._syntax.Version.EnumValue}," );
        writer.WriteLine( $"\tLowest = {versions[0].Version.EnumValue}," );
        writer.WriteLine( $"\tHighest = {versions[^1].Version.EnumValue}" );

        writer.Write( "}" );
    }

    public void GenerateVersionChecker( string path )
    {
        var targetFile = Path.GetFullPath( Path.Combine( this._targetDirectory, path ) );
        CreateDirectoryForFile( targetFile );

        Console.WriteLine( "Creating " + targetFile );

        using var writer = File.CreateText( targetFile );

        WriteUsings( writer );
        writer.WriteLine();
        writer.WriteLine( "namespace Metalama.Framework.Engine.Templating;" );
        writer.WriteLine();

        writer.WriteLine( "internal partial class RoslynVersionSyntaxVerifier" );
        writer.WriteLine( "{" );

        // Process syntax types that are not common to all Roslyn versions.
        foreach ( var type in this._syntax.Types.OfType<Node>().Where( IsVersionSpecificType ) )
        {
            writer.WriteLine( $"\tpublic override void Visit{RemoveSuffix( type.Name, "Syntax" )}( {type.Name} node )" );
            writer.WriteLine( "\t{" );
            writer.WriteLine( $"\t\tthis.VisitVersionSpecificNode( node, {type.MinimalRoslynVersion!.QualifiedEnumValue} );" );
            writer.WriteLine( "\t}" );
        }

        // Process syntax types that are common to all Roslyn versions, but have version-specific fields.
        foreach ( var type in this._syntax.Types.OfType<Node>()
                     .Where( t => !IsVersionSpecificType( t ) && t.Fields.Any( f => IsVersionSpecificField( f ) || GetVersionSpecificKinds( f ).Any() ) ) )
        {
            writer.WriteLine( $"\tpublic override void Visit{RemoveSuffix( type.Name, "Syntax" )}( {type.Name} node )" );
            writer.WriteLine( "\t{" );

            foreach ( var field in type.Fields.Where( f => IsVersionSpecificField( f ) || GetVersionSpecificKinds( f ).Any() ) )
            {
                if ( IsVersionSpecificField( field ) )
                {
                    writer.WriteLine( $"\t\tthis.VisitVersionSpecificField( node.{field.Name}, {field.MinimalRoslynVersion!.QualifiedEnumValue} ); " );
                }
                else
                {
                    writer.WriteLine( $"\t\tswitch ( node.{field.Name}.Kind() )" );
                    writer.WriteLine( "\t\t{" );

                    foreach ( var k in GetVersionSpecificKinds( field ) )
                    {
                        writer.WriteLine( $"\t\t\tcase SyntaxKind.{k.Key.Name}:" );
                        writer.WriteLine( $"\t\t\t\tthis.VisitVersionSpecificFieldKind( node.{field.Name}, {k.Value.QualifiedEnumValue} ); " );
                        writer.WriteLine( $"\t\t\t\tbreak;" );
                    }

                    writer.WriteLine( "\t\t}" );
                }
            }

            writer.WriteLine( "\t}" );
        }

        writer.Write( "}" );

        static bool IsVersionSpecificType( Node t ) => t.MinimalRoslynVersion!.Index > 0;

        static bool IsVersionSpecificField( Field f ) => f.MinimalRoslynVersion!.Index > 0;

        static IEnumerable<KeyValuePair<Kind, RoslynVersion>> GetVersionSpecificKinds( Field f )
        {
            // If the oldest version does not specify any kinds, but newer versions do, don't consider them version-specific.
            if ( f.KindsMinimalRoslynVersions.All( k => k.Value.Index > 0 ) )
            {
                return [];
            }

            return f.KindsMinimalRoslynVersions.Where( k => k.Value.Index > 0 );
        }
    }
    
    
    private static void WriteUsings( StreamWriter writer )
    {
        writer.WriteLine( _autoGeneratedHeader );
        writer.WriteLine( );
        writer.WriteLine( "// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors." );
        writer.WriteLine( "// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained." );
        writer.WriteLine( "// Refer to LICENSE.md in the repository root for complete details." );
        writer.WriteLine();
        writer.WriteLine( "#pragma warning disable CS8669 // Nullability" );
        writer.WriteLine( "#pragma warning disable IDE0005, IDE0040, SA1013, SA1027, SA1205, SA1210, SA1216, SA1508 // Formatting" );
        writer.WriteLine( "using System;" );
        writer.WriteLine( "using System.Linq;" );
        writer.WriteLine( "using System.Collections.Generic;" );
        writer.WriteLine( "using System.Diagnostics.CodeAnalysis;" );
        writer.WriteLine( "using Microsoft.CodeAnalysis;" );
        writer.WriteLine( "using Microsoft.CodeAnalysis.CSharp;" );
        writer.WriteLine( "using Microsoft.CodeAnalysis.CSharp.Syntax;" );
        writer.WriteLine( "using Metalama.Framework.Engine.CompileTime;" );
        writer.WriteLine( "using Metalama.Framework.Engine.Utilities.Roslyn;" );
        writer.WriteLine( "using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;" );
    }

    private static bool IsAutoCreatableToken( Node node, Field field )
    {
        return field is { Type: "SyntaxToken", Kinds: { } }
               && ((field.Kinds.Count == 1 && field.Kinds[0].Name != "IdentifierToken"
                                           && !field.Kinds[0].Name.EndsWith( "LiteralToken", StringComparison.Ordinal ))
                   || (field.Kinds.Count > 1 && field.Kinds.Count == node.Kinds.Count));
    }

    private static IEnumerable<Field> DetermineRedFactoryWithNoAutoCreatableTokenFields( Node nd )
    {
        return nd.Fields.Where( f => !IsAutoCreatableToken( nd, f ) );
    }

    private static bool IsAnyList( string typeName )
    {
        return IsNodeList( typeName ) || IsSeparatedNodeList( typeName ) || typeName == "SyntaxNodeOrTokenList";
    }

    private bool CanBeAutoCreated( Node node, Field field )
    {
        return IsAutoCreatableToken( node, field ) || this.IsAutoCreatableNode( field );
    }

    private bool IsAutoCreatableNode( Field field )
    {
        var referencedNode = this._syntax.GetNode( field.Type );

        return referencedNode != null && this.RequiredFactoryArgumentCount( referencedNode ) == 0;
    }

    private bool IsRequiredFactoryField( Node node, Field field )
    {
        return (!field.IsOptional && !IsAnyList( field.Type ) && !this.CanBeAutoCreated( node, field )) || this.IsValueField( field );
    }

    private int RequiredFactoryArgumentCount( Node nd, bool includeKind = true )
    {
        var count = 0;

        // kind must be specified in factory
        if ( nd.Kinds.Count > 1 && includeKind )
        {
            count++;
        }

        foreach ( var field in nd.Fields )
        {
            if ( this.IsRequiredFactoryField( nd, field ) )
            {
                count++;
            }
        }

        return count;
    }

    private bool IsValueField( Field field ) => !this.IsNodeOrNodeList( field.Type );

    private bool IsNodeOrNodeList( string typeName )
    {
        return this._syntax.IsNode( typeName ) || IsNodeList( typeName ) || IsSeparatedNodeList( typeName ) || typeName == "SyntaxNodeOrTokenList";
    }

    private static bool IsNodeList( string typeName ) => typeName.StartsWith( "SyntaxList<", StringComparison.Ordinal );

    private static bool IsSeparatedNodeList( string typeName ) => typeName.StartsWith( "SeparatedSyntaxList<", StringComparison.Ordinal );

    private static string CommaJoin( params object[] values ) => Join( ", ", values );

    private static string Join( string separator, params object[] values )
    {
        return string.Join(
            separator,
            values.SelectMany(
                v => (v switch
                {
                    string s => [s],
                    IEnumerable<string> ss => ss,
                    _ => throw new InvalidOperationException( "Join must be passed strings or collections of strings" )
                }).Where( s => s != "" ) ) );
    }

    private static string CamelCase( string name )
    {
        if ( char.IsUpper( name[0] ) )
        {
            name = char.ToLowerInvariant( name[0] ) + name.Substring( 1 );
        }

        return FixKeyword( name );
    }

    private static string FixKeyword( string name )
    {
        if ( IsKeyword( name ) )
        {
            return "@" + name;
        }

        return name;
    }

    private static bool IsKeyword( string name )
    {
        switch ( name )
        {
            case "bool":
            case "byte":
            case "sbyte":
            case "short":
            case "ushort":
            case "int":
            case "uint":
            case "long":
            case "ulong":
            case "double":
            case "float":
            case "decimal":
            case "string":
            case "char":
            case "object":
            case "typeof":
            case "sizeof":
            case "null":
            case "true":
            case "false":
            case "if":
            case "else":
            case "while":
            case "for":
            case "foreach":
            case "do":
            case "switch":
            case "case":
            case "default":
            case "lock":
            case "try":
            case "throw":
            case "catch":
            case "finally":
            case "goto":
            case "break":
            case "continue":
            case "return":
            case "public":
            case "protected":
            case "internal":
            case "private":
            case "static":
            case "readonly":
            case "sealed":
            case "const":
            case "new":
            case "override":
            case "abstract":
            case "virtual":
            case "partial":
            case "ref":
            case "out":
            case "in":
            case "where":
            case "params":
            case "this":
            case "base":
            case "namespace":
            case "using":
            case "class":
            case "struct":
            case "interface":
            case "delegate":
            case "checked":
            case "get":
            case "set":
            case "add":
            case "remove":
            case "operator":
            case "implicit":
            case "explicit":
            case "fixed":
            case "extern":
            case "event":
            case "enum":
            case "unsafe":
            case "required":
            case "file":
                return true;

            default:
                return false;
        }
    }

    public static bool IsAnyNodeList( string typeName )
    {
        return IsNodeList( typeName ) || IsSeparatedNodeList( typeName );
    }

    private void GenerateMetaSyntaxRewriter( StreamWriter writer, SyntaxDocument[] syntaxVersions )
    {
        writer.WriteLine( "partial class MetaSyntaxRewriter" );
        writer.WriteLine( "{" );

        var nodes = this._syntax.Types.Where( n => n is not PredefinedNode ).OfType<Node>().ToList();

        foreach ( var node in nodes )
        {
            var nodeTypeName = node.Name;
            var factoryMethodName = RemoveSuffix( nodeTypeName, "Syntax" );

            // Generate the Visit method.
            writer.WriteLine( $"\t[ExcludeFromCodeCoverage]" );
            writer.WriteLine( $"\tpublic override SyntaxNode? Visit{RemoveSuffix( node.Name, "Syntax" )}( {nodeTypeName} node )" );
            writer.WriteLine( "\t{" );
            writer.WriteLine( "\t\tswitch ( this.GetTransformationKind( node ) )" );
            writer.WriteLine( "\t\t{" );

            // Generating Clone is interesting to validate the current code generation, but it is not used.
            writer.WriteLine( "\t\t\tcase TransformationKind.Transform:" );
            writer.WriteLine( $"\t\t\t\treturn this.Transform{factoryMethodName}( node );" );

            writer.WriteLine( "\t\t\tdefault:" );
            writer.WriteLine( $"\t\t\t\treturn base.Visit{RemoveSuffix( node.Name, "Syntax" )}( node );" );
            writer.WriteLine( "\t\t}" );
            writer.WriteLine( "\t}" );

            // Generate the Transform* method. We need to generate it for many target versions of the Roslyn API.
            writer.WriteLine( $"\t[ExcludeFromCodeCoverage]" );
            writer.WriteLine( $"\tprotected virtual ExpressionSyntax Transform{factoryMethodName}( {nodeTypeName} node )" );

            writer.WriteLine( "\t{" );
            writer.WriteLine( "\t\tthis.Indent();" );
            writer.WriteLine( "\t\tExpressionSyntax result;" );

            var roslynApiMinimalVersions = node.Fields.Select( f => f.MinimalRoslynVersion ).Distinct().ToList();
            var roslynApiMaximalVersions = node.Fields.Select( f => f.MaximalRoslynVersion ).Distinct().ToList();

            if ( roslynApiMinimalVersions.Count == 1 && roslynApiMaximalVersions.Count == 1 )
            {
                // All fields in the syntax node are available in all versions of the Roslyn API supporting this syntax type.
                GenerateForFields( "\t\t", node.Fields );
            }
            else
            {
                var relevantRoslynApiVersions = roslynApiMinimalVersions.Union( roslynApiMaximalVersions.Where( v => v != syntaxVersions.Last().Version ) )
                    .OrderBy( v => v.Index )
                    .ToList();

                writer.WriteLine( "\t\tswitch ( this.TargetApiVersion )" );
                writer.WriteLine( "\t\t{" );

                for ( var i = 0; i < relevantRoslynApiVersions.Count; i++ )
                {
                    var minVersion = relevantRoslynApiVersions[i];
                    var maxVersionIndex = i == relevantRoslynApiVersions.Count - 1 ? syntaxVersions.Length - 1 : relevantRoslynApiVersions[i + 1].Index - 1;

                    if ( maxVersionIndex > this._syntax.Version.Index )
                    {
                        maxVersionIndex = this._syntax.Version.Index;
                    }

                    if ( maxVersionIndex < minVersion.Index )
                    {
                        // There are no versions between min and max, which happens when the version range is above the current version,
                        // so do nothing.
                        continue;
                    }

                    for ( var j = minVersion.Index; j <= maxVersionIndex; j++ )
                    {
                        writer.WriteLine( $"\t\t\tcase {syntaxVersions[j].Version.QualifiedEnumValue}:" );
                    }

                    var fields = syntaxVersions[minVersion.Index].GetNode( node.Name )!.Fields;
                    GenerateForFields( "\t\t\t\t", fields );
                    writer.WriteLine( $"\t\t\t\tbreak;" );
                }

                writer.WriteLine( $"\t\t\tdefault:" );
                writer.WriteLine( $"\t\t\t\tthrow new AssertionFailedException();" );
                writer.WriteLine( "\t\t}" );
            }

            void GenerateForFields( string indentation, List<Field> fields )
            {
                writer.Write( $"{indentation}result = InvocationExpression(this.MetaSyntaxFactory.SyntaxFactoryMethod(nameof({factoryMethodName})))" );

                var hasKindParameter = node.Kinds.Count > 1;

                if ( fields.Count == 0 && !hasKindParameter )
                {
                    writer.WriteLine( ";" );
                }
                else
                {
                    writer.WriteLine( ".WithArgumentList(ArgumentList(SeparatedList<ArgumentSyntax>(new SyntaxNodeOrToken[]{" );

                    var appendComma = false;

                    if ( hasKindParameter )
                    {
                        writer.WriteLine( $"{indentation}\tArgument(this.Transform(node.Kind())).WithOptionalLeadingTrivia(this.GetIndentation(), this._generationOptions)," );
                        appendComma = true;
                    }

                    foreach ( var field in fields )
                    {
                        if ( appendComma )
                        {
                            writer.WriteLine( $"{indentation}\tToken(SyntaxKind.CommaToken).WithOptionalTrailingTrivia(GetLineBreak(), this._generationOptions)," );
                        }
                        else
                        {
                            appendComma = true;
                        }

                        writer.WriteLine( $"{indentation}\tArgument(this.Transform(node.{field.Name})).WithOptionalLeadingTrivia(this.GetIndentation(), this._generationOptions)," );
                    }

                    writer.WriteLine( $"{indentation}}})));" );
                }
            }

            writer.WriteLine( "\t\tthis.Unindent();" );
            writer.WriteLine( "\t\treturn result;" );
            writer.WriteLine( "\t}" );
        }
    }

    private void GenerateMetaSyntaxFactory( StreamWriter writer )
    {
        writer.WriteLine( "\tpartial class MetaSyntaxFactoryImpl" );
        writer.WriteLine( "\t{" );

        var nodes = this._syntax.Types.Where( n => n is not PredefinedNode and not AbstractNode ).OfType<Node>().ToList();

        // Generate methods for all types of syntax nodes.
        foreach ( var node in nodes )
        {
            void WriteMethod( List<Field> fields )
            {
                writer.WriteLine( $"\t\t[ExcludeFromCodeCoverage]" );
                writer.Write( $"\t\tpublic InvocationExpressionSyntax {RemoveSuffix( node.Name, "Syntax" )}" );

                writer.Write( "(" );

                var hasKindParameter = node.Kinds.Count > 1;

                writer.Write(
                    CommaJoin(
                        hasKindParameter ? "ExpressionSyntax kind" : "",
                        fields.Select( f => $"ExpressionSyntax {CamelCase( f.Name )}" ) ) );

                writer.WriteLine( ")" );

                var factoryMethod = $"this.SyntaxFactoryMethod( \"{RemoveSuffix( node.Name, "Syntax" )}\" )";

                writer.Write(
                    $"\t\t\t=> SyntaxFactory.InvocationExpression( {factoryMethod}, SyntaxFactory.ArgumentList(SyntaxFactory.SeparatedList<ArgumentSyntax>(" );

                if ( hasKindParameter || fields.Any() )
                {
                    writer.WriteLine( " new ArgumentSyntax[]{" );

                    var appendComma = false;

                    if ( hasKindParameter )
                    {
                        writer.WriteLine();
                        writer.Write( $"\t\t\t\t\tSyntaxFactory.Argument( kind )" );
                        appendComma = true;
                    }

                    foreach ( var field in fields )
                    {
                        if ( appendComma )
                        {
                            writer.WriteLine( ", " );
                        }
                        else
                        {
                            appendComma = true;
                        }

                        writer.Write( $"\t\t\t\t\tSyntaxFactory.Argument( {CamelCase( field.Name )} )" );
                    }

                    writer.Write( "}" );
                }

                writer.Write( "))" );

                writer.WriteLine( ");" );
                writer.WriteLine();
            }

            WriteMethod( node.Fields );

            // Minimal factory.
            if ( node.Fields.Any( f => IsAutoCreatableToken( node, f ) ) )
            {
                var factoryWithNoAutoCreatableTokenFields = new HashSet<Field>( DetermineRedFactoryWithNoAutoCreatableTokenFields( node ) );
                var orderedMinimalFactoryFields = node.Fields.Where( factoryWithNoAutoCreatableTokenFields.Contains ).ToList();
                WriteMethod( orderedMinimalFactoryFields );
            }
            else if ( node.Name == "LiteralExpressionSyntax" )
            {
                // This is added for backward compatibility because SyntaxFactory.LiteralExpression(kind) is implemented manually
                // since Roslyn 4.2.0.

                WriteMethod( new List<Field>() );
            }
        }

        writer.WriteLine( "\t}" );
    }

    public void GenerateHasher( string fileName, string className, bool isCompileTime )
    {
        var path = Path.GetFullPath( Path.Combine( this._targetDirectory, fileName ) );
        CreateDirectoryForFile( path );

        Console.WriteLine( "Creating " + path );

        using var writer = File.CreateText( path );

        WriteUsings( writer );
        writer.WriteLine( "using K4os.Hash.xxHash;" );
        writer.WriteLine();
        writer.WriteLine( "namespace Metalama.Framework.DesignTime.Pipeline.Diff" );
        writer.WriteLine( "{" );
        writer.WriteLine( $"\tpublic class {className} : BaseCodeHasher" );
        writer.WriteLine( "\t{" );
        writer.WriteLine( $"\t\tpublic {className}(XXH64 hasher) : base(hasher) {{}}" );

        writer.WriteLine();

        var nodes = this._syntax.Types.OfType<Node>();

        foreach ( var node in nodes )
        {
            var nodeType = node.Name;

            writer.WriteLine( $"\t\t[ExcludeFromCodeCoverage]" );
            writer.WriteLine( $"\t\tpublic override void Visit{RemoveSuffix( nodeType, "Syntax" )}( {nodeType} node )" );
            writer.WriteLine( "\t\t{" );

            void ProcessField( Field field )
            {
                var fieldName = field.Name;
                var fieldType = field.Type;

                switch ( fieldType )
                {
                    case "bool":
                        return;
                }

                if ( !isCompileTime && IgnoreFieldContentInRunTimeCode( fieldType ) )
                {
                    writer.WriteLine( $"\t\t\t// Skipping content of {fieldName} because it is irrelevant at design time for non-compile-time code." );

                    writer.WriteLine( $"\t\t\tthis.HashValue( node.{fieldName} is null );" );

                    return;
                }

                if ( fieldType == "SyntaxToken" )
                {
                    var fieldTokenKinds = field.Kinds;
                    var isTrivialToken = fieldTokenKinds.All( IsTrivialToken );

                    if ( isTrivialToken )
                    {
                        writer.WriteLine( $"\t\t\tthis.VisitTrivialToken( node.{fieldName} );" );

                        return;
                    }
                    else
                    {
                        writer.WriteLine( $"\t\t\tthis.VisitNonTrivialToken( node.{fieldName} );" );

                        return;
                    }
                }

                writer.WriteLine( $"\t\t\tthis.Visit( node.{fieldName} );" );
            }

            void ProcessParent( List<TreeTypeChild> children )
            {
                foreach ( var field in children.OfType<Field>() )
                {
                    ProcessField( field );
                }

                foreach ( var choice in children.OfType<Choice>() )
                {
                    ProcessParent( choice.Children );
                }

                foreach ( var sequence in children.OfType<Sequence>() )
                {
                    ProcessParent( sequence.Children );
                }
            }

            ProcessParent( node.Children );

            writer.WriteLine( "\t\t}" ); // End of method
        }

        writer.WriteLine( "\t}" ); // End of class
        writer.Write( "}" );   // End of namespace
    }

    private static bool IgnoreFieldContentInRunTimeCode( string fieldType )
    {
        return fieldType switch
        {
            "BlockSyntax" => true,
            "ArrowExpressionClauseSyntax" => true,
            "EqualsValueClauseSyntax" => true,
            _ => false
        };
    }

    private static bool IsTrivialToken( Kind tokenKind )
    {
        return tokenKind.Name switch
        {
            "StringLiteralToken" => false,
            "CharacterLiteralToken" => false,
            "NumericLiteralToken" => false,
            "IdentifierToken" => false,
            _ => true
        };
    }

    public void GeneratePartialUpdate( string fileName )
    {
        var path = Path.GetFullPath( Path.Combine( this._targetDirectory, fileName ) );
        CreateDirectoryForFile( path );

        Console.WriteLine( "Creating " + path );

        using var writer = File.CreateText( path );

        WriteUsings( writer );

        writer.WriteLine();
        writer.WriteLine( "namespace Metalama.Framework.Engine.Utilities.Roslyn;" );
        writer.WriteLine();
        writer.WriteLine( "public static class SyntaxNodePartialUpdateExtensions" );
        writer.WriteLine( "{" );

        writer.WriteLine( "\tpublic readonly struct Option<T>( T value )" );
        writer.WriteLine( "\t{" );
        writer.WriteLine( "\t\tpublic T? GetValueOrDefault() => value;" );
        writer.WriteLine( "\t\tpublic bool HasValue { get; } = true;" );
        writer.WriteLine( "\t\tpublic static implicit operator Option<T>( T value ) => new( value );" );
        writer.WriteLine( "\t}" );

        foreach ( var node in this._syntax.Types.OfType<Node>() )
        {
            var nodeType = node.Name;

            writer.WriteLine( $"\tpublic static {nodeType} PartialUpdate(" );
            writer.Write( $"\t\tthis {nodeType} node" );

            foreach ( var field in node.Fields )
            {
                writer.WriteLine( "," );

                var fieldType = field.Type;

                if ( field.IsOptional && fieldType != "SyntaxToken" )
                {
                    fieldType += '?';
                }
                else if ( fieldType == "SyntaxList<SyntaxToken>" )
                {
                    fieldType = "SyntaxTokenList";
                }

                writer.Write( $"\t\tOption<{fieldType}> {CamelCase( field.Name )} = default" );
            }

            writer.WriteLine( " )" );

            writer.WriteLine( "\t\t=> node.Update(" );

            var lastField = node.Fields.Last();

            foreach ( var field in node.Fields )
            {
                var parameterName = CamelCase( field.Name );

                writer.Write( $"\t\t\t{parameterName}.HasValue ? {parameterName}.GetValueOrDefault()! : node.{field.Name}" );

                writer.WriteLine( field == lastField ? " );" : "," );
            }
        }

        writer.Write( "}" );
    }
}