// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

// ReSharper disable MissingIndent
// ReSharper disable BadExpressionBracesIndent

using Metalama.Framework.Engine.SyntaxGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;

namespace Metalama.Framework.Engine.Linking;

/// <summary>
/// Represents a static delegate field that has to be generated by the linker and is potentially shared between multiple declarations.
/// </summary>
public class StaticDelegateInfo
{
    public INamedTypeSymbol ContainingType { get; }

    public INamedTypeSymbol DelegateType { get; }

    public Func<SyntaxGenerationContext, ExpressionSyntax> InitializeExpressionFunc { get; }

    public StaticDelegateInfo( INamedTypeSymbol containingType, INamedTypeSymbol delegateType, Func<SyntaxGenerationContext, ExpressionSyntax> initializeExpressionFunc )
    {
        this.ContainingType = containingType;
        this.DelegateType = delegateType;
        this.InitializeExpressionFunc = initializeExpression;
    }
}