using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Extensions.DependencyInjection.AspectTests.Advice.LazyOptional_DesignTime
{
  partial class TargetClass
  {
    private IFormatProvider _formatProvider
    {
      get
      {
        return default;
      }
    }
    private Func<IFormatProvider> _formatProviderFunc;
    private IFormatProvider? _formatProviderCache;
    public TargetClass([AspectGenerated] Func<IFormatProvider>? formatProvider) : this()
    {
    }
    public TargetClass(int x, IFormatProvider existingParameter, [AspectGenerated] Func<IFormatProvider>? formatProvider) : this(x, existingParameter)
    {
    }
  }
}