using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Extensions.DependencyInjection.AspectTests.Advice.Programmatic_DesignTime
{
  partial class TargetClass
  {
    private IFormatProvider _formatProvider;
    public TargetClass([AspectGenerated] IFormatProvider? formatProvider = null) : this()
    {
    }
  }
}