// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;

namespace Metalama.Patterns.Contracts;

/// <summary>
/// A disposable cookie returned by the <c>SuspendInvariants</c> method generated by the <see cref="InvariantAttribute"/> aspect.
/// </summary>
[PublicAPI]
public struct SuspendInvariantsCookie : IDisposable
{
    private readonly InvariantSuspensionCounter _counter;
    private bool _disposed;

    public SuspendInvariantsCookie( InvariantSuspensionCounter counter )
    {
        this._counter = counter;
    }

    public void Dispose()
    {
        if ( !this._disposed )
        {
            this._counter.Decrement();
            this._disposed = true;
        }
    }
}