// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using Metalama.Compiler;
using Metalama.Framework.Engine.AspectWeavers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Metalama.Framework.Engine.Formatting
{
    /// <summary>
    /// Provides <see cref="SyntaxAnnotation"/>s and extension methods for marking generated and source code in syntax trees.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Aspect weavers must annotate their generated code so Metalama can properly format it and distinguish it from source code.
    /// Use these methods when transforming syntax trees in <see cref="AspectWeavers.IAspectWeaver"/> implementations.
    /// </para>
    /// <para>
    /// Key methods:
    /// </para>
    /// <list type="bullet">
    /// <item><description><see cref="WithGeneratedCodeAnnotation{T}(T, SyntaxAnnotation)"/>: Mark a node and all children as generated code.</description></item>
    /// <item><description><see cref="WithSourceCodeAnnotation{T}(T)"/>: Mark a node as source code (within a generated tree).</description></item>
    /// <item><description><see cref="WithSimplifierAnnotation{T}(T)"/>: Mark a type name for simplification (e.g., remove namespace qualifications).</description></item>
    /// </list>
    /// <para>
    /// The <see cref="AspectWeavers.AspectWeaverContext.GeneratedCodeAnnotation"/> property provides the annotation specific to the current aspect.
    /// </para>
    /// </remarks>
    /// <seealso cref="AspectWeavers.AspectWeaverContext.GeneratedCodeAnnotation"/>
    [PublicAPI]
    public static class FormattingAnnotations
    {
        /// <summary>
        /// Annotation used to mark locals and 'return;' statement that may be redundant. Currently we are not doing anything with them,
        /// but we could.
        /// </summary>
        public static SyntaxAnnotation PossibleRedundantAnnotation { get; } = new( "Metalama_PossibleRedundant" );

        /// <summary>
        /// Gets an annotation that means that the code has been generated by Metalama, but not by an aspect.
        /// </summary>
        internal static SyntaxAnnotation SystemGeneratedCodeAnnotation { get; } = new( MetalamaCompilerAnnotations.GeneratedCodeAnnotationKind, null );

        /// <summary>
        /// Gets the kind of annotations that means that the code has been generated by Metalama or by an aspect.
        /// </summary>
        internal static string GeneratedCodeAnnotationKind => MetalamaCompilerAnnotations.GeneratedCodeAnnotationKind;

        private static SyntaxAnnotation[]? _simplifier;

        /// <summary>
        /// Gets an annotation that means that the syntax stems from source code. This can be added to a child node of a node annotated
        /// with the <c>WithGeneratedCodeAnnotation</c> method. This is a synonym for <see cref="MetalamaCompilerAnnotations.SourceCodeAnnotation"/>.
        /// </summary>
        public static SyntaxAnnotation SourceCodeAnnotation => MetalamaCompilerAnnotations.SourceCodeAnnotation;

        /// <summary>
        /// Gets an annotation that means that a qualified type must be simplified. This is equivalent to <c>Simplifier.Annotation</c>.
        /// </summary>
        internal static void Initialize( SyntaxAnnotation value )
        {
            // This property must be set by the engine assembly because we don't want a dependency on workspaces here.
            _simplifier = [value];
        }

        /// <summary>
        /// Marks a syntax node for simplification (e.g., removing unnecessary namespace qualifications from type names).
        /// </summary>
        /// <typeparam name="T">The type of syntax node.</typeparam>
        /// <param name="node">The node to mark.</param>
        /// <returns>The node with the simplifier annotation.</returns>
        public static T WithSimplifierAnnotation<T>( this T node ) where T : SyntaxNode => node.WithAdditionalAnnotations( _simplifier );

        [return: NotNullIfNotNull( "node" )]
        private static T? WithAnnotationInsideBlock<T>( this T? node, SyntaxAnnotation annotation, bool addToBrackets = false )
            where T : SyntaxNode
        {
            switch ( node )
            {
                case BlockSyntax block:
                    var annotatedBlock = (T) (object) block.WithStatements(
                        SyntaxFactory.List( block.Statements.Select( s => s.WithAnnotationInsideBlock( annotation, true ) ) ) );

                    if ( addToBrackets )
                    {
                        annotatedBlock = annotatedBlock.WithAdditionalAnnotations( annotation );
                    }

                    return annotatedBlock;

                default:
                    return node?.WithAdditionalAnnotations( annotation );
            }
        }

        /// <summary>
        /// Annotates a syntax node with an annotation meaning that the syntax node and all its children are generated.
        /// The annotation is typically obtained from <see cref="AspectWeaverContext.GeneratedCodeAnnotation"/>, but it can also
        /// be created from <see cref="MetalamaCompilerAnnotations.CreateGeneratedCodeAnnotation"/>.
        /// </summary>
        /// <param name="node">The input node.</param>
        /// <param name="annotation">A <see cref="SyntaxAnnotation"/> of kind <see cref="MetalamaCompilerAnnotations.GeneratedCodeAnnotationKind"/>.</param>
        /// <returns>The annotated node.</returns>
        public static SyntaxToken WithGeneratedCodeAnnotation( this SyntaxToken node, SyntaxAnnotation annotation )
            => node.WithAdditionalAnnotations( annotation );

        /// <summary>
        /// Annotates a syntax node with an annotation meaning that the syntax node and all its children are generated, except whose marked with <see cref="WithSourceCodeAnnotation{T}"/>.
        /// The annotation is typically obtained from <see cref="AspectWeaverContext.GeneratedCodeAnnotation"/>, but it can also
        /// be created from <see cref="MetalamaCompilerAnnotations.CreateGeneratedCodeAnnotation"/>.
        /// </summary>
        /// <param name="node">The input node.</param>
        /// <param name="annotation">A <see cref="SyntaxAnnotation"/> of kind <see cref="MetalamaCompilerAnnotations.GeneratedCodeAnnotationKind"/>.</param>
        /// <returns>The annotated node.</returns>
        [return: NotNullIfNotNull( "node" )]
        public static T? WithGeneratedCodeAnnotation<T>( this T? node, SyntaxAnnotation annotation )
            where T : SyntaxNode
            => node?.WithAnnotationInsideBlock( annotation );

        /// <summary>
        /// Annotates a syntax trivia with an annotation meaning that it is generated code.
        /// </summary>
        /// <param name="trivia">The trivia to annotate.</param>
        /// <param name="annotation">The generated code annotation, typically from <see cref="AspectWeaverContext.GeneratedCodeAnnotation"/>.</param>
        /// <returns>The annotated trivia.</returns>
        public static SyntaxTrivia WithGeneratedCodeAnnotation( this in SyntaxTrivia trivia, SyntaxAnnotation annotation )
            => trivia.WithAdditionalAnnotations( annotation );

        /// <summary>
        /// Annotates a syntax node with an annotation meaning that the syntax node and all its children are user code.
        /// The annotation is typically obtained from <see cref="AspectWeaverContext.GeneratedCodeAnnotation"/>, but it can also
        /// be created from <see cref="MetalamaCompilerAnnotations.CreateGeneratedCodeAnnotation"/>.
        /// </summary>
        /// <param name="node">The input node.</param>
        /// <returns>The annotated node.</returns>
        [return: NotNullIfNotNull( "node" )]
        public static T? WithSourceCodeAnnotation<T>( this T? node )
            where T : SyntaxNode
            => node?.WithAnnotationInsideBlock( SourceCodeAnnotation );

        /// <summary>
        /// Marks a syntax node as source code only if it is not already marked as generated code.
        /// </summary>
        /// <typeparam name="T">The type of syntax node.</typeparam>
        /// <param name="node">The node to potentially mark.</param>
        /// <returns>The node with the source code annotation if not already generated; otherwise, the original node.</returns>
        [return: NotNullIfNotNull( "node" )]
        public static T WithSourceCodeAnnotationIfNotGenerated<T>( this T node )
            where T : SyntaxNode
            => !node.HasAnnotations( MetalamaCompilerAnnotations.GeneratedCodeAnnotationKind )
                ? node.WithSourceCodeAnnotation()
                : node;

        /// <summary>
        /// Copies the formatting annotations (source or generated code) from one node to another.
        /// </summary>
        /// <typeparam name="T">The type of syntax node.</typeparam>
        /// <param name="node">The node to annotate.</param>
        /// <param name="source">The node to copy annotations from.</param>
        /// <returns>The target node with the same formatting annotations as the source node.</returns>
        public static T WithFormattingAnnotationsFrom<T>( this T node, SyntaxNode source )
            where T : SyntaxNode
        {
            if ( source.HasAnnotation( SourceCodeAnnotation ) )
            {
                return node.WithSourceCodeAnnotation();
            }
            else if ( source.GetAnnotations( MetalamaCompilerAnnotations.GeneratedCodeAnnotationKind ).FirstOrDefault() is { } annotation )
            {
                return node.WithGeneratedCodeAnnotation( annotation );
            }
            else
            {
                return node;
            }
        }
    }
}