// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;

namespace Metalama.Patterns.Observability;

/// <summary>
/// Attribute generated by the <see cref="ObservableAttribute"/> aspect on <c>OnChildPropertyChanged</c> and
/// <c>OnObservablePropertyChanged</c> methods, indicating which property expressions are observed by these methods.
/// </summary>
/// <remarks>
/// <para>
/// This attribute forms a contract between base types and derived types in class hierarchies. It informs derived
/// types about which properties the base class monitors for changes, allowing derived classes to efficiently add
/// their own change handling logic.
/// </para>
/// <para>
/// The <c>OnChildPropertyChanged</c> method is called when a property of a child object (i.e., an object stored
/// in a field or property of the current type) has changed. The <c>OnObservablePropertyChanged</c> method is called
/// when a property implementing <see cref="System.ComponentModel.INotifyPropertyChanged"/> has changed, providing
/// both the old and new values to allow derived classes to subscribe and unsubscribe from change events.
/// </para>
/// </remarks>
/// <seealso cref="ObservableAttribute"/>
/// <seealso href="@observability-standard-cases"/>
[PublicAPI]
[AttributeUsage( AttributeTargets.Method )]
public sealed class ObservedExpressionsAttribute : Attribute
{
    // ReSharper disable once UnusedParameter.Local
    /// <summary>
    /// Initializes a new instance of the <see cref="ObservedExpressionsAttribute"/> class.
    /// </summary>
    /// <param name="parentPropertyPaths">
    /// The parent property paths which the declaring class monitors for reference and child property changes,
    /// and for which <c>OnChildPropertyChanged</c> or <c>OnObservablePropertyChanged</c> will be called.
    /// </param>
    public ObservedExpressionsAttribute( params string[] parentPropertyPaths ) { }
}