// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either an MIT license
// or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Backstage.Commands;
using Metalama.Framework.DesignTime.Diagnostics;
using Metalama.Testing.AspectTesting;
using Metalama.Tool.Divorce;
using Spectre.Console.Cli;
using System.Threading.Tasks;

namespace Metalama.Tool
{
    internal static class Program
    {
        private static async Task<int> Main( string[] args )
        {
            var app = new CommandApp();
            var options = new BackstageCommandOptions( new ApplicationInfo() );
            options.AddConfigurationFileAdapter<UserDiagnosticsConfiguration>();
            options.AddConfigurationFileAdapter<TestRunnerOptions>();

            BackstageCommandFactory.ConfigureCommandApp(
                app,
                options,
                ConfigureMoreCommands );

            return await app.RunAsync( args );

            void ConfigureMoreCommands( IConfigurator config )
            {
                config.AddCommand<DivorceCommand>( "divorce" )
                    .WithData( options )
                    .WithDescription( "Copies code generated by Metalama back into your source code, in case you wanted to stop using Metalama." );

                config.AddCommand<InfoCommand>( "info" )
                    .WithData( options )
                    .WithDescription( "Displays diagnostic information about the 'metalama' global tool." );

                config.AddCommand<VersionCommand>( "version" )
                    .WithData( options )
                    .WithDescription( "Displays the version of the 'metalama' global tool." );
            }
        }
    }
}