using System;
using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Framework.Tests.AspectTests.Tests.Aspects.AppendParameter.Preserved_DesignTime
{
  partial class A
  {
    public A(int id, [AspectGenerated] DateTime creationTime) : this(id)
    {
    }
  }
}