using System;
using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Framework.Tests.AspectTests.Tests.Aspects.AppendParameter.PullNullableTypeAtDesignTime
{
  partial class TargetClass
  {
    public TargetClass([AspectGenerated] IFormatProvider? formatProvider = null) : this()
    {
    }
    public TargetClass(int x, [AspectGenerated] IFormatProvider? formatProvider = null) : this(x)
    {
    }
  }
}