using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Framework.Tests.AspectTests.Tests.Aspects.AppendParameter.ReplaceParameter_Covariant_DesignTime
{
  partial class Derived
  {
    public Derived(int x, string name, [AspectGenerated] ICovariant<Derived> service = null) : this(x, name)
    {
    }
  }
}