using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Framework.Tests.AspectTests.Tests.Aspects.AppendParameter.ReplaceParameter_ImplicitCtor_DesignTime
{
  partial class Base
  {
    public Base([AspectGenerated] ICovariant<Base> service = null)
    {
    }
  }
}