using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Framework.Tests.AspectTests.Tests.Aspects.AppendParameter.ReplaceParameter_MultiLevel_DesignTime
{
  partial class Middle
  {
    public Middle(int x, [AspectGenerated] ICovariant<Middle> service = null) : this(x)
    {
    }
  }
}