// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Aspects;
using Metalama.Framework.Code.Invokers;
using System.Reflection;

namespace Metalama.Framework.Code
{
    /// <summary>
    /// Represents an instance constructor or a static constructor.
    /// </summary>
    /// <seealso cref="IMethodBase"/>
    /// <seealso cref="IConstructorInvoker"/>
    /// <seealso cref="ConstructorInitializerKind"/>
    /// <seealso cref="ConstructorAspect"/>
    /// <seealso href="@overriding-constructors"/>
    /// <seealso href="@introducing-constructor-parameters"/>
    public interface IConstructor : IMethodBase, IConstructorInvoker
    {
        /// <summary>
        /// Gets a value indicating whether this constructor is the primary constructor of the type.
        /// </summary>
        /// <remarks>
        /// Primary constructors are recognized only for the current compilation.
        /// </remarks>
        bool IsPrimary { get; }

        /// <summary>
        /// Gets a <see cref="ConstructorInitializerKind" /> that specifies the initializer semantics of the constructor.
        /// </summary>
        ConstructorInitializerKind InitializerKind { get; }

        /// <summary>
        /// Gets a <see cref="ConstructorInfo"/> that represents the current constructor at run time.
        /// </summary>
        /// <returns>A <see cref="ConstructorInfo"/> that can be used only in run-time code.</returns>
        /// <remarks>
        /// <para>
        /// This method generates run-time code that retrieves the <see cref="ConstructorInfo"/> object for the current
        /// constructor. While Metalama is designed to eliminate the need for reflection in most scenarios, this method
        /// is useful when you need to pass constructor metadata to APIs that require <see cref="ConstructorInfo"/> objects.
        /// </para>
        /// <para>
        /// <b>Warning:</b> The code generated by this method relies on constructor signatures and may break if your
        /// project is obfuscated. Consider using constructor invokers (such as
        /// <see cref="Invokers.IConstructorInvoker.Invoke(object?[])"/>) when possible, as this approach is obfuscation-safe.
        /// </para>
        /// </remarks>
        /// <seealso cref="IMethodBase.ToMethodBase"/>
        /// <seealso cref="IMemberOrNamedType.ToMemberInfo"/>
        /// <seealso href="@reflection"/>
        ConstructorInfo ToConstructorInfo();

        /// <summary>
        /// Gets the definition of the constructor. If the current declaration is a constructor of
        /// a generic type instance, this returns the constructor in the generic type definition. Otherwise, it returns the current instance.
        /// </summary>
        new IConstructor Definition { get; }

        /// <inheritdoc cref="IDeclaration.ToRef"/>
        new IRef<IConstructor> ToRef();
    }
}