// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Aspects;
using System;
using System.Collections.Generic;

namespace Metalama.Framework.Code
{
    /// <summary>
    /// Allows to get instances of the <see cref="IType"/> interface or to test for type equality or inheritance.
    /// </summary>
    /// <seealso cref="IType"/>
    /// <seealso cref="INamedType"/>
    /// <seealso cref="TypeFactory"/>
    /// <seealso cref="ICompilation"/>
    [CompileTime]
    public interface IDeclarationFactory
    {
        /// <summary>
        /// Get type based on its full name, as used in reflection.
        /// </summary>
        /// <remarks>
        /// <para>
        /// For nested types, this means using <c>+</c>, e.g. to get <see cref="System.Environment.SpecialFolder"/>, use <c>System.Environment+SpecialFolder</c>.
        /// </para>
        /// <para>
        /// For generic type definitions, this requires using <c>`</c>, e.g. to get <c>List&lt;T&gt;</c>, use <c>System.Collections.Generic.List`1</c>.
        /// </para>
        /// <para>
        /// Constructed generic types (e.g. <c>List&lt;int&gt;</c>) are not supported, for those, use <see cref="GenericExtensions.WithTypeArguments(IMethod, IType[])"/>.
        /// </para>
        /// </remarks>
        INamedType GetTypeByReflectionName( string reflectionName );

        /// <summary>
        /// Gets an <see cref="IType"/> given a reflection <see cref="Type"/>.
        /// </summary>
        IType GetTypeByReflectionType( Type type );

        /// <summary>
        /// Gets an <see cref="INamedType"/> given a reflection <see cref="Type"/>.
        /// </summary>
        INamedType GetNamedTypeByReflectionType( Type type );

        /// <summary>
        /// Gets a <see cref="INamedType"/> representing a given <see cref="SpecialType"/>.
        /// </summary>
        INamedType GetSpecialType( SpecialType specialType );

        /// <summary>
        /// Gets a declaration from a serialized identifier generated by <see cref="IRef.ToSerializableId"/>.
        /// </summary>
        IDeclaration GetDeclarationFromId( SerializableDeclarationId declarationId );

        /// <summary>
        /// Translates a compilation element to the current compilation context, optionally applying a generic context for type parameter substitution.
        /// </summary>
        /// <typeparam name="T">The type of compilation element to translate.</typeparam>
        /// <param name="compilationElement">The compilation element to translate.</param>
        /// <param name="genericContext">Optional generic context for type parameter substitution.</param>
        /// <returns>The translated compilation element, or <c>null</c> if the input is <c>null</c> or cannot be translated.</returns>
        T? Translate<T>(
            T? compilationElement,
            IGenericContext? genericContext = null )
            where T : class, ICompilationElement;

        /// <summary>
        /// Gets a type from a serialized type identifier, optionally substituting generic arguments.
        /// </summary>
        /// <param name="serializableTypeId">The serialized type identifier.</param>
        /// <param name="genericArguments">Optional dictionary mapping generic parameter names to their type arguments.</param>
        /// <returns>The type corresponding to the serialized identifier.</returns>
        IType GetTypeFromId( SerializableTypeId serializableTypeId, IReadOnlyDictionary<string, IType>? genericArguments );

        /// <summary>
        /// Creates a tuple type with the specified element types (given as <see cref="IType"/>) and default element names.
        /// </summary>
        ITupleType CreateTupleType( IEnumerable<IType> elementTypes );

        /// <summary>
        /// Creates a tuple type with the specified element types (given as reflection <see cref="Type"/>'s) and default element names.
        /// </summary>
        ITupleType CreateTupleType( IEnumerable<Type> elementTypes );

        /// <summary>
        /// Creates a tuple type with the specified element types (given as <see cref="IType"/>'s) and names.
        /// </summary>
        ITupleType CreateTupleType( IEnumerable<(IType Type, string Name)> elementTypes );

        /// <summary>
        /// Creates a tuple type with the specified element types (given as reflection <see cref="Type"/>'s) and names.
        /// </summary>
        ITupleType CreateTupleType( IEnumerable<(Type Type, string Name)> elementTypes );

        /// <summary>
        /// Creates a tuple type with the specified parameters as elements.
        /// </summary>
        ITupleType CreateTupleType( IEnumerable<IParameter> elementTypes );
    }
}