// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Aspects;
using System.Reflection;

namespace Metalama.Framework.Code
{
    /// <summary>
    /// Base interface for <see cref="IMethod"/>, <see cref="IFieldOrPropertyOrIndexer"/>, <see cref="IEvent"/>, and <see cref="INamedType"/>.
    /// </summary>
    /// <seealso cref="IMethod"/>
    /// <seealso cref="IFieldOrPropertyOrIndexer"/>
    /// <seealso cref="IEvent"/>
    /// <seealso cref="INamedType"/>
    /// <seealso cref="IMember"/>
    /// <seealso cref="MemberExtensions"/>
    public interface IMemberOrNamedType : INamedDeclaration
    {
        /// <summary>
        /// Gets the member accessibility (or visibility), i.e. <see cref="Accessibility.Private"/>, <see cref="Accessibility.Protected"/>
        /// and so on.
        /// </summary>
        Accessibility Accessibility { get; }

        bool IsAbstract { get; }

        /// <summary>
        /// Gets a value indicating whether the member is <c>static</c>.
        /// </summary>
        bool IsStatic { get; }

        /// <summary>
        /// Gets a value indicating whether the member is <c>sealed</c>.
        /// </summary>
        /// <seealso cref="MemberExtensions.IsOverridable"/>
        bool IsSealed { get; }

        /// <summary>
        /// Gets a value indicating whether the member hides another member defined in base types. When <c>true</c>, this is equivalent to <c>new</c> keyword being <i>expected</i> in the source code although this property will return <c>true</c> even when the <c>new</c> keyword is not present but expected.
        /// </summary>
        bool IsNew { get; }

        /// <summary>
        /// Gets the type containing the current member, or <c>null</c> if the current member is not contained
        /// within a type.
        /// </summary>
        INamedType? DeclaringType { get; }

        /// <summary>
        /// Gets a <see cref="MemberInfo"/> that represents the current member or type at run time.
        /// </summary>
        /// <returns>A <see cref="MemberInfo"/> that can be used only in run-time code.</returns>
        /// <remarks>
        /// <para>
        /// This method generates run-time code that retrieves the <see cref="MemberInfo"/> object for the current
        /// declaration. The actual return type depends on the declaration: <see cref="System.Reflection.FieldInfo"/>
        /// for fields, <see cref="System.Reflection.PropertyInfo"/> for properties, <see cref="System.Reflection.MethodInfo"/>
        /// for methods, and so on.
        /// </para>
        /// <para>
        /// While Metalama is designed to eliminate the need for reflection in most scenarios, this method is useful
        /// when you need to pass member metadata to APIs that require <see cref="MemberInfo"/> objects.
        /// </para>
        /// <para>
        /// <b>Warning:</b> The code generated by this method relies on member names and may break if your project
        /// is obfuscated. Consider using strongly-typed alternatives when possible.
        /// </para>
        /// </remarks>
        /// <seealso cref="IType.ToType"/>
        /// <seealso cref="IMethod.ToMethodInfo"/>
        /// <seealso cref="IField.ToFieldInfo"/>
        /// <seealso cref="IPropertyOrIndexer.ToPropertyInfo"/>
        /// <seealso href="@reflection"/>
        [CompileTimeReturningRunTime]
        MemberInfo ToMemberInfo();

        /// <summary>
        /// Gets a value indicating whether the declaration executes at compile time, at run time, or both.
        /// </summary>
        /// <seealso cref="CompileTimeAttribute"/>
        /// <seealso cref="RunTimeOrCompileTimeAttribute"/>
        ExecutionScope ExecutionScope { get; }

        /// <summary>
        /// Gets the definition of the member or type. If the current declaration is a generic type instance, a generic method instance, or a member of
        /// a generic type instance, this returns the generic definition. Otherwise, it returns the current instance.
        /// </summary>
        IMemberOrNamedType Definition { get; }

        /// <inheritdoc cref="IDeclaration.ToRef"/>
        new IRef<IMemberOrNamedType> ToRef();

        /// <summary>
        /// Gets a value indicating whether the type or member is marked as <c>partial</c> in source code. 
        /// </summary>
        /// <remarks>
        /// To check whether a partial member has an implementation, check the <see cref="IMember.HasImplementation"/> property.
        /// </remarks>
        bool IsPartial { get; }
    }
}