// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using System.Reflection;

namespace Metalama.Framework.Code
{
    /// <summary>
    /// Represents a method or a constructor.
    /// </summary>
    /// <seealso cref="IMethod"/>
    /// <seealso cref="IConstructor"/>
    /// <seealso cref="IHasParameters"/>
    public interface IMethodBase : IHasParameters
    {
        /// <summary>
        /// Gets a <see cref="MethodBase"/> that represents the current method or constructor at run time.
        /// </summary>
        /// <returns>A <see cref="MethodBase"/> that can be used only in run-time code.</returns>
        /// <remarks>
        /// <para>
        /// This method generates run-time code that retrieves the <see cref="MethodBase"/> object (either
        /// <see cref="System.Reflection.MethodInfo"/> or <see cref="System.Reflection.ConstructorInfo"/>) for the current
        /// method or constructor. For more specific return types, use <see cref="IMethod.ToMethodInfo"/> or
        /// <see cref="IConstructor.ToConstructorInfo"/>.
        /// </para>
        /// <para>
        /// While Metalama is designed to eliminate the need for reflection in most scenarios, this method is useful
        /// when you need to pass method metadata to APIs that require <see cref="MethodBase"/> objects.
        /// </para>
        /// <para>
        /// <b>Warning:</b> The code generated by this method relies on method names and signatures, and may break if your
        /// project is obfuscated. Consider using method invokers (see <c>IMethod.Invoke</c>) when possible, as this approach
        /// is obfuscation-safe.
        /// </para>
        /// </remarks>
        /// <seealso cref="IMemberOrNamedType.ToMemberInfo"/>
        /// <seealso cref="IMethod.ToMethodInfo"/>
        /// <seealso cref="IConstructor.ToConstructorInfo"/>
        /// <seealso href="@reflection"/>
        MethodBase ToMethodBase();

        /// <inheritdoc cref="IDeclaration.ToRef"/>
        new IRef<IMethodBase> ToRef();
    }
}