// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Code.DeclarationBuilders;
using System.Reflection;

namespace Metalama.Framework.Code
{
    /// <summary>
    /// Represents a parameter of a method or property.
    /// </summary>
    /// <seealso cref="IParameterBuilder"/>
    /// <seealso cref="IHasParameters"/>
    /// <seealso cref="IMethod"/>
    /// <seealso cref="IConstructor"/>
    /// <seealso cref="IIndexer"/>
    /// <seealso cref="RefKind"/>
    /// <seealso href="@introducing-constructor-parameters"/>
    public interface IParameter : INamedDeclaration, IExpression
    {
        /// <summary>
        /// Gets the parameter position, or <c>-1</c> for <see cref="IMethod.ReturnParameter"/>.
        /// </summary>
        int Index { get; }

        /// <remarks>
        /// Gets the default value of the parameter, or  <c>default</c> if the parameter type is a struct and the default
        /// value of the parameter is the default value of the struct type.
        /// </remarks>
        /// <exception cref="System.InvalidOperationException">The parameter has no default value.</exception>
        TypedConstant? DefaultValue { get; }

        /// <summary>
        /// Gets a value indicating whether the parameter has the <see langword="params" /> modifier.
        /// </summary>
        bool IsParams { get; }

        /// <summary>
        /// Gets a value indicating whether the parameter has the <see langword="this" /> modifier, meaning that the containing method is an extension method.
        /// </summary>
        bool IsThis { get; }

        /// <summary>
        /// Gets the parent <see cref="IMethod"/>, <see cref="IConstructor"/> or <see cref="IIndexer"/>.
        /// Returns <c>null</c> if this parameter is the <see cref="IExtensionBlock.ReceiverParameter"/> of an <see cref="IExtensionBlock"/>.
        /// </summary>
        IHasParameters? DeclaringMember { get; }

        /// <summary>
        /// Gets a <see cref="ParameterInfo"/> that represents the current parameter at run time.
        /// </summary>
        /// <returns>A <see cref="ParameterInfo"/> that can be used only in run-time code.</returns>
        /// <remarks>
        /// <para>
        /// This method generates run-time code that retrieves the <see cref="ParameterInfo"/> object for the current
        /// parameter. While Metalama is designed to eliminate the need for reflection in most scenarios, this method
        /// is useful when you need to pass parameter metadata to APIs that require <see cref="ParameterInfo"/> objects.
        /// </para>
        /// <para>
        /// <b>Warning:</b> The code generated by this method relies on method names and parameter positions, and may
        /// break if your project is obfuscated. Consider using the <see cref="IExpression.Value"/> property to access
        /// parameter values directly when possible, as this approach is obfuscation-safe.
        /// </para>
        /// </remarks>
        /// <seealso cref="IMethod.ToMethodInfo"/>
        /// <seealso cref="IConstructor.ToConstructorInfo"/>
        /// <seealso href="@reflection"/>
        ParameterInfo ToParameterInfo();

        bool IsReturnParameter { get; }

        /// <inheritdoc cref="IDeclaration.ToRef"/>
        new IRef<IParameter> ToRef();
    }
}