// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Aspects;
using System.Reflection;

namespace Metalama.Framework.Code;

/// <summary>
/// A base interface for <see cref="IProperty"/> and <see cref="IIndexer"/>.
/// </summary>
/// <seealso cref="IProperty"/>
/// <seealso cref="IIndexer"/>
/// <seealso cref="IFieldOrPropertyOrIndexer"/>
public interface IPropertyOrIndexer : IFieldOrPropertyOrIndexer
{
    /// <summary>
    /// Gets a <see cref="PropertyInfo"/> that represents the current property or indexer at run time.
    /// </summary>
    /// <returns>A <see cref="PropertyInfo"/> that can be used only in run-time code.</returns>
    /// <remarks>
    /// <para>
    /// This method generates run-time code that retrieves the <see cref="PropertyInfo"/> object for the current
    /// property or indexer. While Metalama is designed to eliminate the need for reflection in most scenarios,
    /// this method is useful when you need to pass property metadata to APIs that require <see cref="PropertyInfo"/> objects.
    /// </para>
    /// <para>
    /// <b>Warning:</b> The code generated by this method relies on property names and may break if your project
    /// is obfuscated. Consider using the <see cref="IExpression.Value"/> property to access property values directly
    /// when possible, as this approach is obfuscation-safe.
    /// </para>
    /// </remarks>
    /// <seealso cref="IMemberOrNamedType.ToMemberInfo"/>
    /// <seealso href="@reflection"/>
    [CompileTimeReturningRunTime]
    PropertyInfo ToPropertyInfo();

    /// <inheritdoc cref="IDeclaration.ToRef"/>
    new IRef<IPropertyOrIndexer> ToRef();
}