[TestAspect]
internal class TargetCode
{
  public TargetCode()
  {
    var members = (object[])GetType().GetField("members", BindingFlags.Instance | BindingFlags.NonPublic)!.GetValue(this)!;
    for (var i = 0; i < members.Length; i++)
    {
      if (members[i] == null)
      {
        throw new Exception($"Member at index {i} was not resolved correctly.");
      }
    }
  }
  private global::System.Object[] members = new global::System.Object[]
  {
    typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetMethod("M", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, new[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMethodException("The method 'RunTimeClass.M(int)' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetMethod("M", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, new[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMethodException("The method 'RunTimeClass.M(int)' could not be found using reflection.")).ReturnParameter,
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetMethod("M", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, new[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMethodException("The method 'RunTimeClass.M(int)' could not be found using reflection.")).GetParameters()[0],
    new global::Metalama.Framework.RunTime.FieldOrPropertyInfo((typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetProperty("P", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingMemberException("The property 'RunTimeClass.P' could not be found using reflection."))),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetProperty("P", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingMemberException("The property 'RunTimeClass.P' could not be found using reflection.")),
    new global::Metalama.Framework.RunTime.FieldOrPropertyInfo((typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetField("<P>k__BackingField", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingFieldException("The field 'RunTimeClass.P.field' could not be found using reflection."))),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetField("<P>k__BackingField", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingFieldException("The field 'RunTimeClass.P.field' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetEvent("E", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingMemberException("The event 'RunTimeClass.E' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetProperty("Item", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, typeof(global::System.Int32), new global::System.Type[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMemberException("The indexer 'RunTimeClass.this[int]' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetProperty("Item", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, typeof(global::System.Int32), new global::System.Type[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMemberException("The indexer 'RunTimeClass.this[int]' could not be found using reflection.")).GetIndexParameters()[0],
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeClass).GetConstructor(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance, null, global::System.Type.EmptyTypes, null) ?? throw new global::System.MissingMethodException("The constructor 'RunTimeClass.RunTimeClass()' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetMethod("M", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, new[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMethodException("The method 'RunTimeOrCompileTimeClass.M(int)' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetMethod("M", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, new[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMethodException("The method 'RunTimeOrCompileTimeClass.M(int)' could not be found using reflection.")).ReturnParameter,
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetMethod("M", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, new[] { typeof(global::System.Int32) }, null) ?? throw new global::System.MissingMethodException("The method 'RunTimeOrCompileTimeClass.M(int)' could not be found using reflection.")).GetParameters()[0],
    new global::Metalama.Framework.RunTime.FieldOrPropertyInfo((typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetProperty("P", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingMemberException("The property 'RunTimeOrCompileTimeClass.P' could not be found using reflection."))),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetProperty("P", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingMemberException("The property 'RunTimeOrCompileTimeClass.P' could not be found using reflection.")),
    new global::Metalama.Framework.RunTime.FieldOrPropertyInfo((typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetField("<P>k__BackingField", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingFieldException("The field 'RunTimeOrCompileTimeClass.P.field' could not be found using reflection."))),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetField("<P>k__BackingField", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingFieldException("The field 'RunTimeOrCompileTimeClass.P.field' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetEvent("E", global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance) ?? throw new global::System.MissingMemberException("The event 'RunTimeOrCompileTimeClass.E' could not be found using reflection.")),
    (typeof(global::Metalama.Framework.Tests.AspectTests.Tests.Aspects.Misc.MemberInfoAsIExpression_CompileTime.RunTimeOrCompileTimeClass).GetConstructor(global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.Instance, null, global::System.Type.EmptyTypes, null) ?? throw new global::System.MissingMethodException("The constructor 'RunTimeOrCompileTimeClass.RunTimeOrCompileTimeClass()' could not be found using reflection."))
  };
}