<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.15</MetalamaCompilerVersion>
    <MetalamaReleaseVersion>2026.1.23</MetalamaReleaseVersion>
    <MetalamaReleaseMainVersion>2026.1.23</MetalamaReleaseMainVersion>
  </PropertyGroup>
</Project>