<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2027.0.0</MetalamaCompilerVersion>
    <MetalamaReleaseVersion>2027.0.0</MetalamaReleaseVersion>
    <MetalamaReleaseMainVersion>2027.0.0</MetalamaReleaseMainVersion>
  </PropertyGroup>
</Project>