// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either an MIT license
// or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using Metalama.Framework.Diagnostics;
using Metalama.Framework.Eligibility;
using Metalama.Framework.Engine.AspectOrdering;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace Metalama.Framework.Engine.Aspects
{
    /// <summary>
    /// Exposes the semantics of an aspect class used by the implementation of the aspect.
    /// </summary>
    internal interface IAspectClassImpl : IAspectClass, IEligibilityRule<IDeclaration>, IDiagnosticSource
    {
        ImmutableArray<TemplateClass> TemplateClasses { get; }

        /// <summary>
        /// Gets the <see cref="SyntaxAnnotation"/> that must be added to code generated by the current aspect class.
        /// </summary>
        SyntaxAnnotation GeneratedCodeAnnotation { get; }

        ImmutableArray<AspectLayer> Layers { get; }

        /// <summary>
        /// Gets the eligibility of a an aspect instance of the current aspect class without when knowing whether the aspect instance is inheritable.
        /// </summary>
        EligibleScenarios GetEligibility( IDeclaration obj, bool isInheritable );

        /// <summary>
        /// Gets the closure of all descendant classes.
        /// </summary>
        IReadOnlyCollection<IAspectClassImpl> DescendantClassesAndSelf { get; }
    }
}