// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using System.Diagnostics.CodeAnalysis;
using System.Text.RegularExpressions;

namespace Metalama.Framework.DesignTime.SourceGeneration;

/// <summary>
/// Renders and parses the per-project touch-marker <c>.cs</c> file. The file lives under <c>obj/</c> and is
/// included in the compilation as a regular <c>&lt;Compile&gt;</c> source. Roslyn re-runs source generators
/// when a <c>&lt;Compile&gt;</c> file changes, so overwriting the file's <see cref="TouchFileHelper.MarkerFieldName"/>
/// GUID is what invalidates the design-time source generator cache.
/// </summary>
internal static class TouchFileRenderer
{
    private const string _guidPlaceholder = "__GUID__";

    private static readonly string _template =
        $$"""
        // <auto-generated />
        // Do not modify. Do not use — this class has no compile-time meaning. It exists only at design
        // time, where Metalama overwrites the {{TouchFileHelper.MarkerFieldName}} GUID on every pipeline run to invalidate the
        // source generator cache.
        #nullable enable
        namespace {{TouchFileHelper.MarkerNamespace}}
        {
            [global::System.Runtime.CompilerServices.CompilerGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Obsolete("Design-time only. Do not reference.", true)]
            internal static class {{TouchFileHelper.MarkerTypeName}}
            {
                public const string {{TouchFileHelper.MarkerFieldName}} = "__GUID__";
            }
        }

        """;

    private static readonly Regex _touchIdRegex = new(
        $@"public\s+const\s+string\s+{Regex.Escape( TouchFileHelper.MarkerFieldName )}\s*=\s*""([^""]*)""",
        RegexOptions.Compiled );

#pragma warning disable CA1307 // string.Replace(string, string) is the only overload available on net472.
    public static string Render( string guid ) => _template.Replace( _guidPlaceholder, guid );
#pragma warning restore CA1307

    public static bool TryReadGuid( string filePath, [NotNullWhen( true )] out string? guid )
    {
        if ( !File.Exists( filePath ) )
        {
            guid = null;

            return false;
        }

        var content = File.ReadAllText( filePath );
        var match = _touchIdRegex.Match( content );

        if ( !match.Success )
        {
            guid = null;

            return false;
        }

        guid = match.Groups[1].Value;

        return true;
    }
}
