// Copyright (c) SharpCrafters s.r.o. See the LICENSE.md file in the root directory of this repository root for details.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Metalama.Framework.Engine.Pipeline.DesignTime;

public static class DesignTimeSyntaxTreeHelper
{
    public static SyntaxTriviaList GetHeader()
    {
        const string generatedByMetalama = " Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.";

        return TriviaList(
            Trivia(
                DocumentationCommentTrivia(
                    SyntaxKind.SingleLineDocumentationCommentTrivia,
                    List(
                        new XmlNodeSyntax[]
                        {
                            XmlText()
                                .WithTextTokens(
                                    TokenList(
                                        XmlTextLiteral(
                                            TriviaList( DocumentationCommentExterior( "///" ) ),
                                            " ",
                                            " ",
                                            TriviaList() ) ) ),
                            XmlExampleElement(
                                    SingletonList<XmlNodeSyntax>(
                                        XmlText()
                                            .WithTextTokens(
                                                TokenList(
                                                    XmlTextNewLine(
                                                        TriviaList(),
                                                        "\n",
                                                        "\n",
                                                        TriviaList() ),
                                                    XmlTextLiteral(
                                                        TriviaList( DocumentationCommentExterior( "///" ) ),
                                                        generatedByMetalama,
                                                        generatedByMetalama,
                                                        TriviaList() ),
                                                    XmlTextNewLine(
                                                        TriviaList(),
                                                        "\n",
                                                        "\n",
                                                        TriviaList() ),
                                                    XmlTextLiteral(
                                                        TriviaList( DocumentationCommentExterior( "///" ) ),
                                                        " ",
                                                        " ",
                                                        TriviaList() ) ) ) ) )
                                .WithStartTag( XmlElementStartTag( XmlName( Identifier( "generated" ) ) ) )
                                .WithEndTag(
                                    XmlElementEndTag( XmlName( Identifier( "generated" ) ) )
                                        .WithGreaterThanToken( Token( SyntaxKind.GreaterThanToken ) ) ),
                            XmlText()
                                .WithTextTokens(
                                    TokenList(
                                        XmlTextNewLine(
                                            TriviaList(),
                                            "\n",
                                            "\n",
                                            TriviaList() ) ) )
                        } ) ) ),
            LineFeed,
            LineFeed );
    }
}