using Metalama.Framework.RunTime;
/// <auto-generated>
/// Generated by Metalama to support the code editing experience. This is NOT the code that gets executed.
/// </auto-generated>
namespace Metalama.Extensions.DependencyInjection.AspectTests.Aspect.EarlyRequired_DesignTime
{
  partial class TargetClass
  {
    public TargetClass([AspectGenerated] IFormatProvider? formatProvider) : this()
    {
    }
  }
}