// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using System.ComponentModel;

namespace Metalama.Patterns.Wpf;

/// <summary>
/// An asynchronous implementation of <see cref="System.Windows.Input.ICommand"/> that uses delegates for the execute and can-execute logic,
/// without accepting a command parameter. This class is typically generated by the <see cref="CommandAttribute"/> aspect
/// for methods returning <see cref="Task"/> or when <see cref="CommandAttribute.Background"/> is <c>true</c>.
/// </summary>
/// <remarks>
/// <para>This class implements <see cref="IAsyncCommand"/> and <see cref="INotifyPropertyChanged"/>, exposing properties
/// like <see cref="BaseAsyncDelegateCommand.IsRunning"/>, <see cref="BaseAsyncDelegateCommand.CanCancel"/>, and <see cref="BaseAsyncDelegateCommand.ExecutionTask"/>
/// to monitor command execution state.</para>
/// <para>By default, the command cannot be executed concurrently. This can be changed via <see cref="CommandAttribute.SupportsConcurrentExecution"/>.</para>
/// </remarks>
/// <seealso cref="AsyncDelegateCommand{T}"/>
/// <seealso cref="DelegateCommand"/>
/// <seealso cref="DelegateCommandExecution"/>
/// <seealso cref="CommandAttribute"/>
/// <seealso href="@wpf-command"/>
[PublicAPI]
public sealed class AsyncDelegateCommand : BaseAsyncDelegateCommand
{
    private readonly Func<bool>? _canExecute;
    private readonly Func<CancellationToken, Task> _execute;

    /// <summary>
    /// Initializes a new instance of the <see cref="AsyncDelegateCommand"/> class, without <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal AsyncDelegateCommand(
        Func<CancellationToken, Task> execute,
        Func<bool>? canExecute,
        bool supportsCancellation,
        bool supportsConcurrentExecution ) : base( supportsCancellation, supportsConcurrentExecution )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AsyncDelegateCommand"/> class, with <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal AsyncDelegateCommand(
        Func<CancellationToken, Task> execute,
        Func<bool> canExecute,
        INotifyPropertyChanged canExecutePropertyChangeNotifier,
        string canExecutePropertyName,
        bool supportsCancellation,
        bool supportsConcurrentExecution ) : base( canExecutePropertyChangeNotifier, canExecutePropertyName, supportsCancellation, supportsConcurrentExecution )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Gets a value indicating whether the command can be executed.
    /// Returns <c>false</c> if the command is already running and concurrent execution is not supported,
    /// or if the <c>CanExecute</c> delegate returns <c>false</c>.
    /// </summary>
    public bool CanExecute => this.OuterCanExecute( null );

    /// <summary>
    /// Executes the command asynchronously and returns a <see cref="DelegateCommandExecution"/> that can be used
    /// to track and cancel the execution.
    /// </summary>
    /// <returns>A <see cref="DelegateCommandExecution"/> representing the execution.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the command cannot be executed.</exception>
    public DelegateCommandExecution Execute() => this.OuterExecute( null );

    private protected override bool InnerCanExecute( object? parameter ) => this._canExecute == null || this._canExecute.Invoke();

    private protected override Task InnerExecuteAsync( object? parameter, CancellationToken cancellationToken ) => this._execute( cancellationToken );
}