// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using System.ComponentModel;

namespace Metalama.Patterns.Wpf;

/// <summary>
/// An asynchronous implementation of <see cref="System.Windows.Input.ICommand"/> that uses delegates for the execute and can-execute logic,
/// accepting a command parameter of type <typeparamref name="T"/>. This class is typically generated by the <see cref="CommandAttribute"/> aspect
/// for methods returning <see cref="Task"/> or when <see cref="CommandAttribute.Background"/> is <c>true</c>.
/// </summary>
/// <typeparam name="T">The type of the command parameter.</typeparam>
/// <remarks>
/// <para>This class implements <see cref="IAsyncCommand"/> and <see cref="INotifyPropertyChanged"/>, exposing properties
/// like <see cref="BaseAsyncDelegateCommand.IsRunning"/>, <see cref="BaseAsyncDelegateCommand.CanCancel"/>, and <see cref="BaseAsyncDelegateCommand.ExecutionTask"/>
/// to monitor command execution state.</para>
/// <para>By default, the command cannot be executed concurrently. This can be changed via <see cref="CommandAttribute.SupportsConcurrentExecution"/>.</para>
/// </remarks>
/// <seealso cref="AsyncDelegateCommand"/>
/// <seealso cref="DelegateCommand{T}"/>
/// <seealso cref="DelegateCommandExecution"/>
/// <seealso cref="CommandAttribute"/>
/// <seealso href="@wpf-command"/>
[PublicAPI]
public sealed class AsyncDelegateCommand<T> : BaseAsyncDelegateCommand
{
    private readonly Func<T, bool>? _canExecute;
    private readonly Func<T, CancellationToken, Task> _execute;

    /// <summary>
    /// Initializes a new instance of the <see cref="AsyncDelegateCommand{T}"/> class, without <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal AsyncDelegateCommand(
        Func<T, CancellationToken, Task> execute,
        Func<T, bool>? canExecute,
        bool supportsCancellation,
        bool supportsConcurrentExecution ) : base( supportsCancellation, supportsConcurrentExecution )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="AsyncDelegateCommand{T}"/> class, with <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal AsyncDelegateCommand(
        Func<T, CancellationToken, Task> execute,
        Func<T, bool> canExecute,
        INotifyPropertyChanged canExecutePropertyChangeNotifier,
        string canExecutePropertyName,
        bool supportsCancellation,
        bool supportsConcurrentExecution ) : base( canExecutePropertyChangeNotifier, canExecutePropertyName, supportsCancellation, supportsConcurrentExecution )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Determines whether the command can be executed with the specified parameter.
    /// Returns <c>false</c> if the command is already running and concurrent execution is not supported,
    /// or if the <c>CanExecute</c> delegate returns <c>false</c>.
    /// </summary>
    /// <param name="parameter">The command parameter.</param>
    /// <returns><c>true</c> if the command can be executed; otherwise, <c>false</c>.</returns>
    public bool CanExecute( T parameter ) => this.OuterCanExecute( parameter );

    /// <summary>
    /// Executes the command asynchronously with the specified parameter and returns a <see cref="DelegateCommandExecution"/>
    /// that can be used to track and cancel the execution.
    /// </summary>
    /// <param name="parameter">The command parameter.</param>
    /// <returns>A <see cref="DelegateCommandExecution"/> representing the execution.</returns>
    /// <exception cref="InvalidOperationException">Thrown when the command cannot be executed.</exception>
    public DelegateCommandExecution Execute( T parameter ) => this.OuterExecute( parameter );

    private protected override bool InnerCanExecute( object? parameter ) => this._canExecute == null || this._canExecute.Invoke( (T) parameter! );

    private protected override Task InnerExecuteAsync( object? parameter, CancellationToken cancellationToken )
        => this._execute( (T) parameter!, cancellationToken );
}