// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using System.ComponentModel;

namespace Metalama.Patterns.Wpf;

/// <summary>
/// An implementation of <see cref="System.Windows.Input.ICommand"/> that uses delegates for the execute and can-execute logic,
/// without accepting a command parameter. This class is typically generated by the <see cref="CommandAttribute"/> aspect.
/// </summary>
/// <remarks>
/// <para>This class implements <see cref="INotifyPropertyChanged"/> to notify when <see cref="CanExecute"/> changes.
/// When integrated with an <see cref="INotifyPropertyChanged"/> implementation for the <c>CanExecute</c> property,
/// the <see cref="BaseDelegateCommand.CanExecuteChanged"/> event is automatically raised.</para>
/// </remarks>
/// <seealso cref="DelegateCommand{T}"/>
/// <seealso cref="AsyncDelegateCommand"/>
/// <seealso cref="CommandAttribute"/>
/// <seealso href="@wpf-command"/>
[PublicAPI]
public sealed class DelegateCommand : BaseDelegateCommand, INotifyPropertyChanged
{
    private readonly Func<bool>? _canExecute;
    private readonly Action _execute;

    /// <summary>
    /// Initializes a new instance of the <see cref="DelegateCommand"/> class, without <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal DelegateCommand( Action execute, Func<bool>? canExecute )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DelegateCommand"/> class, with <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal DelegateCommand(
        Action execute,
        Func<bool> canExecute,
        INotifyPropertyChanged canExecutePropertyChangeNotifier,
        string canExecutePropertyName ) : base( canExecutePropertyChangeNotifier, canExecutePropertyName )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Executes the command. This overload is obsolete because this command type does not accept parameters.
    /// </summary>
    /// <param name="parameter">This parameter is ignored.</param>
    [Obsolete( "This command does not accept any arguments." )]
    public void Execute( object? parameter ) => this.Execute();

    /// <summary>
    /// Executes the command by invoking the execute delegate.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the command cannot be executed (i.e., <see cref="CanExecute"/> returns <c>false</c>).</exception>
    public void Execute()
    {
        if ( !this.CanExecute )
        {
            throw new InvalidOperationException( "Command cannot be executed." );
        }

        this._execute();
    }

    /// <summary>
    /// Gets a value indicating whether the command can be executed.
    /// Returns <c>true</c> if no <c>CanExecute</c> delegate was provided, or if the delegate returns <c>true</c>.
    /// </summary>
    public bool CanExecute => this._canExecute == null || this._canExecute();

    private protected override bool CanExecuteCore( object? parameter )
    {
        if ( parameter != null )
        {
            throw new ArgumentOutOfRangeException( nameof(parameter), "The parameter must be null." );
        }

        return this.CanExecute;
    }

    private protected override void ExecuteCore( object? parameter )
    {
        if ( parameter != null )
        {
            throw new ArgumentOutOfRangeException( nameof(parameter), "The parameter must be null." );
        }

        this.Execute();
    }

    private protected override void OnCanExecuteChanged()
    {
        base.OnCanExecuteChanged();
        this.PropertyChanged?.Invoke( this, new PropertyChangedEventArgs( nameof(this.CanExecute) ) );
    }

    /// <inheritdoc />
    public event PropertyChangedEventHandler? PropertyChanged;
}