// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using JetBrains.Annotations;
using System.ComponentModel;
using System.Windows.Input;

namespace Metalama.Patterns.Wpf;

/// <summary>
/// An implementation of <see cref="ICommand"/> that uses delegates for the <see cref="Execute"/> and <see cref="CanExecute"/> logic,
/// accepting a command parameter of type <typeparamref name="T"/>. This class is typically generated by the <see cref="CommandAttribute"/> aspect.
/// </summary>
/// <typeparam name="T">The type of the command parameter.</typeparam>
/// <remarks>
/// <para>When integrated with an <see cref="INotifyPropertyChanged"/> implementation for the <c>CanExecute</c> property,
/// the <see cref="BaseDelegateCommand.CanExecuteChanged"/> event is automatically raised.</para>
/// </remarks>
/// <seealso cref="DelegateCommand"/>
/// <seealso cref="AsyncDelegateCommand{T}"/>
/// <seealso cref="CommandAttribute"/>
/// <seealso href="@wpf-command"/>
[PublicAPI]
public sealed class DelegateCommand<T> : BaseDelegateCommand
{
    private readonly Func<T, bool>? _canExecute;
    private readonly Action<T> _execute;

    /// <summary>
    /// Initializes a new instance of the <see cref="DelegateCommand{T}"/> class, without <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal DelegateCommand( Action<T> execute, Func<T, bool>? canExecute )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DelegateCommand{T}"/> class, with <see cref="INotifyPropertyChanged"/> integration.
    /// </summary>
    internal DelegateCommand(
        Action<T> execute,
        Func<T, bool> canExecute,
        INotifyPropertyChanged canExecutePropertyChangeNotifier,
        string canExecutePropertyName ) : base( canExecutePropertyChangeNotifier, canExecutePropertyName )
    {
        this._execute = execute;
        this._canExecute = canExecute;
    }

    /// <summary>
    /// Executes the command with the specified parameter.
    /// </summary>
    /// <param name="parameter">The command parameter.</param>
    /// <exception cref="InvalidOperationException">Thrown when the command cannot be executed (i.e., <see cref="CanExecute"/> returns <c>false</c>).</exception>
    public void Execute( T parameter )
    {
        if ( !this.CanExecute( parameter ) )
        {
            throw new InvalidOperationException( "Command cannot be executed." );
        }

        this._execute( parameter );
    }

    /// <summary>
    /// Determines whether the command can be executed with the specified parameter.
    /// Returns <c>true</c> if no <c>CanExecute</c> delegate was provided, or if the delegate returns <c>true</c>.
    /// </summary>
    /// <param name="parameter">The command parameter.</param>
    /// <returns><c>true</c> if the command can be executed; otherwise, <c>false</c>.</returns>
    public bool CanExecute( T parameter ) => this._canExecute == null || this._canExecute( parameter );

    private protected override bool CanExecuteCore( object? parameter )
    {
        if ( parameter is not T value )
        {
            throw new ArgumentOutOfRangeException( nameof(parameter) );
        }

        return this.CanExecute( value );
    }

    private protected override void ExecuteCore( object? parameter ) => this.Execute( (T) parameter! );
}