// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Engine.CompileTime;
using Metalama.Framework.Engine.Diagnostics;
using Metalama.Framework.Engine.Templating;
using Metalama.Framework.Engine.Utilities;
using Metalama.Testing.UnitTesting;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Linq;
using Xunit;

namespace Metalama.Framework.Tests.UnitTests.Templating;

/// <summary>
/// Tests of <see cref="RoslynVersionSyntaxVerifier"/>.
/// </summary>
/// <remarks>
/// The overrides of the verifier are generated by the prepare step. Each of them calls the base implementation, which
/// visits the children of the node. These tests check that the walk reaches syntax nested below a node that is itself
/// version-specific, and below a node that merely carries a version-specific field or token. See issue #2034.
/// </remarks>
public sealed class RoslynVersionSyntaxVerifierTests : UnitTestClass
{
    /// <summary>
    /// Runs the verifier over a single parsed statement and returns both the maximal used version and the reported
    /// diagnostics.
    /// </summary>
    private static (RoslynApiVersion MaximalUsedVersion, Diagnostic[] Diagnostics) Verify(
        string statement,
        LanguageVersion maximalAcceptableLanguageVersion )
    {
        var parsedStatement = SyntaxFactory.ParseStatement( statement, options: SupportedCSharpVersions.DefaultParseOptions );

        Assert.DoesNotContain( parsedStatement.GetDiagnostics(), d => d.Severity == DiagnosticSeverity.Error );

        var diagnostics = new DiagnosticBag();
        var verifier = new RoslynVersionSyntaxVerifier( diagnostics, maximalAcceptableLanguageVersion );
        verifier.Visit( parsedStatement );

        return (verifier.MaximalUsedVersion, diagnostics.ToArray());
    }

    [Fact]
    public void StatementWithoutVersionSpecificSyntaxUsesTheLowestVersion()
    {
        var result = Verify( """Console.WriteLine( "a" + "b" );""", LanguageVersion.CSharp10 );

        Assert.Equal( RoslynApiVersion.Lowest, result.MaximalUsedVersion );
        Assert.Empty( result.Diagnostics );
    }

    /// <summary>
    /// A raw string literal is a token of C# 11 carried by a literal expression. When it is an operand of a binary
    /// expression, it is reached only if the override of <c>VisitBinaryExpression</c> visits the children of the node.
    /// </summary>
    [Fact]
    public void RawStringInBinaryExpressionIsDetected()
    {
        const string statement = """"
                                 Console.WriteLine( """raw""" + "b" );
                                 """";

        var result = Verify( statement, SupportedCSharpVersions.Latest );

        Assert.Equal( RoslynApiVersion.V4_4_0, result.MaximalUsedVersion );
        Assert.Empty( result.Diagnostics );
    }

    /// <summary>
    /// A collection expression is a node of C# 12. When it is the right operand of an assignment, it is reached only
    /// if the override of <c>VisitAssignmentExpression</c> visits the children of the node.
    /// </summary>
    [Fact]
    public void CollectionExpressionInAssignmentIsDetected()
    {
        var result = Verify( "array = [1, 2];", SupportedCSharpVersions.Latest );

        Assert.Equal( RoslynApiVersion.V4_8_0, result.MaximalUsedVersion );
        Assert.Empty( result.Diagnostics );
    }

    /// <summary>
    /// A list pattern is a node of C# 11. When it stands in the hole of an interpolated string, it is reached only if
    /// the override of <c>VisitInterpolatedStringExpression</c> visits the children of the node.
    /// </summary>
    [Fact]
    public void ListPatternInInterpolatedStringIsDetected()
    {
        var result = Verify( """Console.WriteLine( $"{array is [1]}" );""", SupportedCSharpVersions.Latest );

        Assert.Equal( RoslynApiVersion.V4_4_0, result.MaximalUsedVersion );
        Assert.Empty( result.Diagnostics );
    }

    /// <summary>
    /// A raw string literal that stands inside a collection expression is reached only if the override of
    /// <c>VisitCollectionExpression</c> visits the children of the node. The collection expression itself requires
    /// C# 12 and the raw string literal requires C# 11, so a project limited to C# 10 must receive a diagnostic for
    /// both of them.
    /// </summary>
    [Fact]
    public void ForbiddenSyntaxIsReportedBelowAVersionSpecificNode()
    {
        const string rawString = """"
                                 """raw"""
                                 """";

        const string statement = """"
                                 string[] array = ["""raw"""];
                                 """";

        var result = Verify( statement, LanguageVersion.CSharp10 );

        Assert.Equal( RoslynApiVersion.V4_8_0, result.MaximalUsedVersion );

        // The diagnostic on the collection expression is reported even when the walk is truncated. The diagnostic on
        // the raw string literal is the one that requires the walk to descend into the collection expression.
        var rawStringPosition = statement.IndexOf( rawString, StringComparison.Ordinal );

        Assert.Contains( result.Diagnostics, d => d.Location.SourceSpan.Start == rawStringPosition );
    }
}
