// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Code;
using Metalama.Framework.Code.SyntaxBuilders;
using Metalama.Framework.Engine.SyntaxGeneration;
using Metalama.Framework.Engine.SyntaxSerialization;
using Metalama.Framework.Engine.Templating;
using Metalama.Framework.Engine.Templating.Expressions;
using Metalama.Testing.UnitTesting;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Linq;
using System.Runtime.ExceptionServices;
using System.Text;
using System.Threading;
using Xunit;

namespace Metalama.Framework.Tests.UnitTests.Templating;

/// <summary>
/// Tests the rendering of a <see cref="UserExpression"/> by its <see cref="UserExpression.ToString"/> method.
/// </summary>
public sealed class UserExpressionToStringTests : UnitTestClass
{
    /// <summary>
    /// The stack size of the threads that the tests create, like in hosts such as Visual Studio.
    /// </summary>
    private const int _threadStackSize = 1024 * 1024;

    /// <summary>
    /// Verifies that an array of shallow expressions is rendered with normalized whitespace.
    /// </summary>
    [Fact]
    public void ArrayOfShallowExpressions()
    {
        var text = this.ArrayToString( "a.M()", "b" );

        Assert.Equal( "new global::System.Object[]\r\n{\r\n    a.M(),\r\n    b\r\n}", text );
    }

    /// <summary>
    /// Verifies that an array whose element is a deep expression can be rendered on a thread with a stack of 1 MB
    /// (issue #2083). The array creation expression is generated by <see cref="ContextualSyntaxGenerator.ArrayCreationExpression"/>.
    /// </summary>
    [Fact]
    public void ArrayOfDeepExpression()
    {
        var text = this.ArrayToString( CreateDeepExpression( "this" ) );

        Assert.StartsWith( "new global::System.Object[]", text, StringComparison.Ordinal );
        Assert.Contains( "{\r\nthis.M().M()", text, StringComparison.Ordinal );
        Assert.EndsWith( ".M()}", text, StringComparison.Ordinal );
    }

    /// <summary>
    /// Verifies that the rendering of a deep expression does not change the content of an interpolated string.
    /// </summary>
    [Fact]
    public void ArrayOfDeepExpressionWithInterpolatedString()
    {
        var text = this.ArrayToString( CreateDeepExpression( "$\"a{b}c{d:N2}\"" ) );

        Assert.Contains( "{\r\n$\"a{b}c{d:N2}\".M().M()", text, StringComparison.Ordinal );
    }

    /// <summary>
    /// Verifies that the shallow elements of an array that also contains a deep element are normalized, and that spaces are
    /// added between the tokens of a generated deep element.
    /// </summary>
    [Fact]
    public void ArrayOfDeepAndGeneratedExpressions()
    {
        var generatedIsExpression = SyntaxFactory.BinaryExpression(
            SyntaxKind.IsExpression,
            SyntaxFactory.IdentifierName( "x" ),
            SyntaxFactory.PredefinedType( SyntaxFactory.Token( SyntaxKind.IntKeyword ) ) );

        var deepGeneratedExpression = SyntaxFactory.BinaryExpression(
            SyntaxKind.IsExpression,
            CreateDeepExpression( "y" ),
            SyntaxFactory.PredefinedType( SyntaxFactory.Token( SyntaxKind.IntKeyword ) ) );

        var text = this.ArrayToString( generatedIsExpression, deepGeneratedExpression );

        Assert.Contains( "x is int,", text, StringComparison.Ordinal );
        Assert.Contains( "y.M().M()", text, StringComparison.Ordinal );
        Assert.EndsWith( ".M()is int}", text, StringComparison.Ordinal );
    }

    /// <summary>
    /// Parses a chain of 1,400 calls to a method <c>M</c> on the given receiver. The depth of the resulting expression is about 2,800.
    /// </summary>
    private static ExpressionSyntax CreateDeepExpression( string receiver )
    {
        const int callCount = 1400;

        var code = new StringBuilder();
        code.Append( receiver );

        for ( var i = 0; i < callCount; i++ )
        {
            code.Append( ".M()" );
        }

        return SyntaxFactory.ParseExpression( code.ToString() );
    }

    /// <summary>
    /// Parses the given expressions and calls <see cref="ArrayToString(ExpressionSyntax[])"/>.
    /// </summary>
    private string ArrayToString( params string[] elements ) => this.ArrayToString( elements.Select( e => SyntaxFactory.ParseExpression( e ) ).ToArray() );

    /// <summary>
    /// Creates an <see cref="ArrayUserExpression"/> whose elements are the given expressions, and returns the result of its
    /// <see cref="UserExpression.ToString"/> method, called on a thread with a stack of <see cref="_threadStackSize"/> bytes.
    /// </summary>
    private string ArrayToString( params ExpressionSyntax[] elements )
    {
        using var testContext = this.CreateTestContext();
        var compilation = testContext.CreateCompilationModel( "" );
        var objectType = compilation.Factory.GetSpecialType( SpecialType.Object );
        var syntaxSerializationContext = new SyntaxSerializationContext( compilation, SyntaxGenerationOptions.Formatted );

        return RunOnThread(
            () =>
            {
                using ( TemplateExpansionContext.WithTestingContext( syntaxSerializationContext, testContext.ServiceProvider ) )
                {
                    var arrayBuilder = new ArrayBuilder( objectType );

                    foreach ( var element in elements )
                    {
                        arrayBuilder.Add( new SyntaxUserExpression( element, objectType ) );
                    }

                    return new ArrayUserExpression( arrayBuilder ).ToString();
                }
            } );
    }

    /// <summary>
    /// Runs the given function on a new thread with a stack of <see cref="_threadStackSize"/> bytes, and returns its result
    /// or rethrows its exception.
    /// </summary>
    private static T RunOnThread<T>( Func<T> func )
    {
        var result = default(T);
        ExceptionDispatchInfo? exception = null;

        var thread = new Thread(
            () =>
            {
                try
                {
                    result = func();
                }
                catch ( Exception e )
                {
                    exception = ExceptionDispatchInfo.Capture( e );
                }
            },
            _threadStackSize );

        thread.Start();
        thread.Join();

        exception?.Throw();

        return result!;
    }
}
