// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Code;
using Metalama.Framework.Code.SyntaxBuilders;
using Metalama.Framework.Engine.SyntaxGeneration;
using Metalama.Framework.Engine.SyntaxSerialization;
using Metalama.Framework.Engine.Templating;
using Metalama.Framework.Engine.Templating.Expressions;
using Metalama.Testing.UnitTesting;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Runtime.ExceptionServices;
using System.Text;
using System.Threading;
using Xunit;

namespace Metalama.Framework.Tests.UnitTests.Templating;

/// <summary>
/// Tests the rendering of a <see cref="UserExpression"/> by its <see cref="UserExpression.ToString"/> method.
/// </summary>
public sealed class UserExpressionToStringTests : UnitTestClass
{
    /// <summary>
    /// The stack size of the threads that the tests create, like in hosts such as Visual Studio.
    /// </summary>
    private const int _threadStackSize = 1024 * 1024;

    /// <summary>
    /// Verifies that an array of shallow expressions is rendered with normalized whitespace.
    /// </summary>
    [Fact]
    public void ArrayOfShallowExpressions()
    {
        var text = this.ArrayToString( "a.M()", "b" );

        Assert.Equal( "new global::System.Object[]\r\n{\r\n    a.M(),\r\n    b\r\n}", text );
    }

    /// <summary>
    /// Verifies that an array whose element is a deep expression can be rendered on a thread with a stack of 1 MB
    /// (issue #2083). The array creation expression is generated by <see cref="ContextualSyntaxGenerator.ArrayCreationExpression"/>.
    /// </summary>
    [Fact]
    public void ArrayOfDeepExpression()
    {
        const int callCount = 1400;

        var code = new StringBuilder();
        code.Append( "this" );

        for ( var i = 0; i < callCount; i++ )
        {
            code.Append( ".M()" );
        }

        var text = this.ArrayToString( code.ToString() );

        Assert.StartsWith( "new global :: System . Object [ ] { this . M ( ) . M ( )", text, StringComparison.Ordinal );
        Assert.EndsWith( ". M ( ) }", text, StringComparison.Ordinal );
    }

    /// <summary>
    /// Creates an <see cref="ArrayUserExpression"/> whose elements are the given expressions, and returns the result of its
    /// <see cref="UserExpression.ToString"/> method, called on a thread with a stack of <see cref="_threadStackSize"/> bytes.
    /// </summary>
    private string ArrayToString( params string[] elements )
    {
        using var testContext = this.CreateTestContext();
        var compilation = testContext.CreateCompilationModel( "" );
        var objectType = compilation.Factory.GetSpecialType( SpecialType.Object );
        var syntaxSerializationContext = new SyntaxSerializationContext( compilation, SyntaxGenerationOptions.Formatted );

        return RunOnThread(
            () =>
            {
                using ( TemplateExpansionContext.WithTestingContext( syntaxSerializationContext, testContext.ServiceProvider ) )
                {
                    var arrayBuilder = new ArrayBuilder( objectType );

                    foreach ( var element in elements )
                    {
                        arrayBuilder.Add( new SyntaxUserExpression( SyntaxFactory.ParseExpression( element ), objectType ) );
                    }

                    return new ArrayUserExpression( arrayBuilder ).ToString();
                }
            } );
    }

    /// <summary>
    /// Runs the given function on a new thread with a stack of <see cref="_threadStackSize"/> bytes, and returns its result
    /// or rethrows its exception.
    /// </summary>
    private static T RunOnThread<T>( Func<T> func )
    {
        var result = default(T);
        ExceptionDispatchInfo? exception = null;

        var thread = new Thread(
            () =>
            {
                try
                {
                    result = func();
                }
                catch ( Exception e )
                {
                    exception = ExceptionDispatchInfo.Capture( e );
                }
            },
            _threadStackSize );

        thread.Start();
        thread.Join();

        exception?.Throw();

        return result!;
    }
}
