// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using System.Runtime.InteropServices;

namespace Metalama.Framework.DesignTime.Contracts.Classification
{
    // The type identifier cannot be modified even during refactoring.

    /// <summary>
    /// An enumeration of classifications of text spans, which typically
    /// map to different colors in the view layer.
    /// </summary>
    [Guid( "7DA04C5D-73B4-4774-9316-27CCAB521B81" )]
    public enum DesignTimeTextSpanClassification
    {
        /// <summary>
        /// No category.
        /// </summary>
        Default,

        /// <summary>
        /// Run-time code.
        /// </summary>
        RunTime,

        /// <summary>
        /// Compile-time code.
        /// </summary>
        CompileTime,

        /// <summary>
        /// Dynamic member.
        /// </summary>
        Dynamic,

        /// <summary>
        /// Compile-time variable.
        /// </summary>
        CompileTimeVariable,

        /// <summary>
        /// Keyword-like member.
        /// </summary>
        TemplateKeyword,

        /// <summary>
        /// A text span has several categories (not implemented).
        /// </summary>
        Conflict,

        /// <summary>
        /// An excluded region, which should not be written to the output file (used for HTML generation).
        /// </summary>
        Excluded,

        /// <summary>
        /// Used to classify the output code and marks the code generated by the aspect or by the framework.
        /// </summary>
        GeneratedCode,

        /// <summary>
        /// Used to classify the output code and marks the source code.
        /// </summary>
        SourceCode
    }
}