// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Backstage;
using Metalama.Framework.ConfigurationFiles;
using Metalama.Tool.Divorce;
using SharpCrafters.Backstage.Commands;
using SharpCrafters.Backstage.Maintenance;
using Spectre.Console.Cli;
using System.Threading.Tasks;

namespace Metalama.Tool
{
    internal static class Program
    {
        private static async Task<int> Main( string[] args )
        {
            var app = new CommandApp();
            // The integrated development environments load the analyzers of Metalama, so the shutdown, kill and cleanup
            // commands report their processes, which the user has to close.
            var options = new BackstageCommandOptions(
                new ApplicationInfo(),
                MetalamaProduct.Instance,
                registerServices: builder => builder.AddDevelopmentEnvironmentShutdownStrategy() );
            options.AddConfigurationFileAdapter<UserDiagnosticsConfiguration>();
            options.AddConfigurationFileAdapter<TestRunnerOptions>();

            BackstageCommandFactory.ConfigureCommandApp(
                app,
                options,
                ConfigureMoreCommands );

            return await app.RunAsync( args );

            void ConfigureMoreCommands( IConfigurator config )
            {
                config.AddCommand<DivorceCommand>( "divorce" )
                    .WithData( options )
                    .WithDescription( "Copies code generated by Metalama back into your source code, in case you wanted to stop using Metalama." );
            }
        }
    }
}