// Copyright (c) 2020-2025 SharpCrafters s.r.o. and contributors.
// SharpCrafters s.r.o. licenses this file to you under either the MIT license or a proprietary license, depending on the repository from which it was obtained.
// Refer to LICENSE.md in the repository root for complete details.

using Metalama.Framework.Engine.Utilities.Roslyn;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Metalama.Framework.Tests.UnitTests.Utilities;

/// <summary>
/// Tests of <see cref="GeneratedCodeClassifier"/>.
/// </summary>
public sealed class GeneratedCodeClassifierTests
{
    /// <summary>
    /// Verifies the rules that classify a syntax tree as generated code: the suffixes and the prefix of the file name, without case, and the
    /// leading comment, with case.
    /// </summary>
    [Theory]
    [InlineData( "Form1.Designer.cs", "", true )]
    [InlineData( "Generated.g.cs", "", true )]
    [InlineData( "Generated.g.i.cs", "", true )]
    [InlineData( "Model.generated.cs", "", true )]
    [InlineData( "TemporaryGeneratedFile_123.cs", "", true )]
    [InlineData( "Program.cs", "// <auto-generated/>\n", true )]
    [InlineData( "Program.cs", "/* <autogenerated> */\n", true )]
    [InlineData( "Program.cs", "// Copyright\n", false )]
    [InlineData( "Program.cs", "", false )]

    // Roslyn compares the file name without case, and the comment marker with case.
    [InlineData( "GENERATED.G.CS", "", true )]
    [InlineData( "Program.cs", "// <AUTO-GENERATED/>\n", false )]
    public void IsGenerated_Rules( string path, string header, bool isGenerated )
        => Assert.Equal( isGenerated, GeneratedCodeClassifier.IsGenerated( CSharpSyntaxTree.ParseText( header + "class C { }", path: path, cancellationToken: TestContext.Current.CancellationToken ) ) );
}
