name: Build on Docker

on: workflow_dispatch

permissions:
  contents: read
  
jobs:

  build:

    runs-on: windows-2022

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Run DockerBuild.ps1 script
      run: pwsh ./DockerBuild.ps1 -c Public --ci --no-sign

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: artifacts/publish/private
        retention-days: 3

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: artifacts/logs
        retention-days: 3